/* ---------- personagens de jogos (só na cópia dos fãs, não vai para o site oficial) ----------
   Mesma regra dos especiais do pets.js: cabeça nas linhas 0 a 8, corpo de 9 a 15, "e" = olho (pisca), "lid" = cor da pálpebra */
(() => {
  /* todos custam 500 (decisão dela); não pintam e não usam roupinhas.
     "group" é o título do grupo na coleção (a coleção mostra um grupo depois do outro) */
  const GRUPO = {
    '🐻 Five Nights at Freddy\'s': ['freddy', 'bonnie', 'chica', 'foxy', 'goldenfreddy', 'springtrap', 'mangle', 'puppet', 'balloonboy', 'circusbaby'],
    '🍄 Super Mario': ['mario', 'luigi', 'peach', 'daisy', 'rosalina', 'toad', 'yoshi', 'bowser', 'boo'],
    '🗡️ Zelda e Kirby': ['link', 'zelda', 'kirby'],
    '⚡ Pokémon': ['pikachu', 'eevee', 'jigglypuff'],
    '🎮 outros jogos': ['sonic', 'tails', 'pacman', 'creeper', 'steve', 'amongus', 'sans', 'hollow'],
    '🎀 Sanrio': ['hellokitty', 'mymelody', 'kuromi', 'cinnamoroll', 'pompompurin'],
    '🎃 Halloween': ['ghostface', 'jason', 'chucky', 'michaelmyers', 'bruxa']
  };
  const grupoDe = id => Object.keys(GRUPO).find(g => GRUPO[g].includes(id));
  const ROWS = {};
  /* piscar sozinho: nos desenhos copiados das referências o olho não vem marcado. Aqui ele é achado
     (manchinhas escuras fechadas na parte de cima do desenho, de preferência duas lado a lado)
     e vira "e", com a pálpebra na cor da pele em volta — igual aos bichinhos */
  const lum = hex => { const n = parseInt(String(hex).slice(1), 16); return .299 * (n >> 16) + .587 * (n >> 8 & 255) + .114 * (n & 255); };
  function autoEyes(rows, pal) {
    const N = rows.length, g = rows.map(r => [...r]), count = {};
    g.forEach(r => r.forEach(ch => { if (ch !== '.') count[ch] = (count[ch] || 0) + 1; }));
    const total = Object.values(count).reduce((a, b) => a + b, 0);
    /* olho = cor escura, ou cor rara (olho azul da Daisy, do Cinnamoroll…) */
    const dark = ch => ch !== '.' && /^#/.test(pal[ch] || '') && (lum(pal[ch]) < 95 || count[ch] <= total * .025);
    let top = N, bot = -1, left = N, right = -1;
    g.forEach((r, y) => r.forEach((ch, x) => { if (ch !== '.') { top = Math.min(top, y); bot = Math.max(bot, y); left = Math.min(left, x); right = Math.max(right, x); } }));
    const H = bot - top + 1, W = right - left + 1, lim = top + Math.floor(H * .62), seen = new Set(), comps = [];
    for (let y = top; y <= lim; y++) for (let x = left; x <= right; x++) {
      if (!dark(g[y][x]) || seen.has(y * N + x)) continue;
      const cells = [], st = [[y, x]]; seen.add(y * N + x); let open = false;
      while (st.length) {
        const [cy, cx] = st.pop(); cells.push([cy, cx]);
        for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) { const c = (g[cy + dy] || [])[cx + dx]; if (c === undefined || c === '.') open = true; }
        [[1, 0], [-1, 0], [0, 1], [0, -1]].forEach(([dy, dx]) => { const ny = cy + dy, nx = cx + dx;
          if (ny >= top && ny <= lim && nx >= 0 && nx < N && dark(g[ny][nx]) && !seen.has(ny * N + nx)) { seen.add(ny * N + nx); st.push([ny, nx]); } });
      }
      if (open) continue;
      const ys = cells.map(c => c[0]), xs = cells.map(c => c[1]);
      const w = Math.max(...xs) - Math.min(...xs) + 1, h = Math.max(...ys) - Math.min(...ys) + 1;
      if (cells.length > W * H / 25 || w > W / 3.5 || h > H / 4) continue;
      comps.push({cells, n:cells.length, cx:xs.reduce((a, b) => a + b) / xs.length, cy:ys.reduce((a, b) => a + b) / ys.length});
    }
    let pick = null, best = 1e9;
    for (let i = 0; i < comps.length; i++) for (let j = i + 1; j < comps.length; j++) {
      const a = comps[i], b = comps[j], dy = Math.abs(a.cy - b.cy), dx = Math.abs(a.cx - b.cx);
      if (dy > Math.max(1.5, H / 12) || dx < W / 8) continue;
      /* mais alto no rosto e mais escuro = mais cara de olho (a bochecha fica mais embaixo) */
      const s = dy * 2 + Math.abs(a.n - b.n) / Math.max(a.n, b.n) * 4 + ((a.cy + b.cy) / 2 - top) / H * 6 + lum(pal[g[a.cells[0][0]][a.cells[0][1]]]) / 255 * 2 - (a.n + b.n) / (W * H) * 20;
      if (s < best) { best = s; pick = [a, b]; }
    }
    if (!pick && comps.length) pick = [comps.slice().sort((a, b) => b.n - a.n)[0]]; // de lado: um olho só
    if (!pick) return {rows, pal};
    const eye = pick[0].cells[0], eyeLetter = g[eye[0]][eye[1]], around = {};
    pick.forEach(c => c.cells.forEach(([y, x]) => {
      [[1, 0], [-1, 0], [0, 1], [0, -1]].forEach(([dy, dx]) => { const ch = (g[y + dy] || [])[x + dx]; if (ch && ch !== '.' && !dark(ch)) around[ch] = (around[ch] || 0) + 1; });
    }));
    const lid = Object.entries(around).sort((a, b) => b[1] - a[1])[0];
    if (!lid) return {rows, pal};
    pick.forEach(c => c.cells.forEach(([y, x]) => { g[y][x] = 'e'; }));
    const out = g.map(r => r.join(''));
    out.eyeFrom = {eye:eyeLetter, lid:lid[0]};
    return {rows:out, pal:Object.assign({}, pal, {e:pal[eyeLetter], lid:lid[0], o:pal.o || pal[eyeLetter]})};
  }
  /* olhos marcados à mão onde o automático erra: cells = [linha, coluna]; box = [linha1, linha2, col1, col2]
     (só as letras de "only", ou todas menos "except"); lid = cor da pálpebra; line = risquinho do olho fechado.
     null = não pisca (Bowser de lado, Among Us só tem visor) */
  const EYES = {
    bonnie: {cells:[[15, 22], [15, 23], [15, 24], [15, 28], [15, 29], [15, 30]], lid:'f', line:'a'},
    chica: {cells:[[11, 16], [11, 17], [11, 18], [11, 22], [11, 23], [11, 24]], lid:'b', line:'a'},
    foxy: {cells:[[10, 24], [10, 25], [10, 26], [11, 24], [11, 25], [11, 26]], lid:'d', line:'a'},
    freddy: {cells:[[12, 20], [12, 21], [12, 22], [12, 26], [12, 27], [12, 28]], lid:'c', line:'a'},
    goldenfreddy: {box:[[11, 12, 18, 20], [11, 12, 24, 26]], lid:'b', line:'a'},
    mangle: {box:[[9, 12, 8, 11], [9, 12, 15, 18]], except:'b', lid:'b', line:'f'},
    puppet: {box:[[4, 5, 10, 12], [4, 5, 14, 16]], only:'a', lid:'w', line:'a'},
    balloonboy: {box:[[28, 32, 34, 39], [28, 32, 41, 46]], only:'pqa', lid:'n', line:'a'},
    circusbaby: {cells:[[9, 17], [10, 17], [10, 18], [9, 26], [10, 25], [10, 26]], lid:'g', line:'w'},
    kirby: {box:[[8, 11, 9, 10], [8, 11, 12, 13]], except:'f', lid:'f', line:'a'},
    peach: {cells:[[16, 24], [17, 24], [16, 28], [17, 28]], lid:'k', line:'a'},
    daisy: {cells:[[9, 12], [10, 12], [9, 15], [10, 15]], lid:'h', line:'a'},
    rosalina: {cells:[[18, 29], [18, 30], [19, 29], [19, 30], [20, 28], [20, 29], [20, 30]], lid:'g', line:'a'},
    link: {cells:[[11, 8], [11, 9], [11, 14], [11, 15]], lid:'d', line:'a'},
    zelda: {cells:[[10, 9], [11, 8], [11, 9], [10, 14], [11, 14], [11, 15]], lid:'d', line:'a'},
    sonic: {box:[[5, 9, 13, 17]], except:'b', lid:'b', line:'a'},
    jigglypuff: {box:[[19, 29, 9, 16], [25, 36, 26, 35]], only:'wdfg', lid:'b', line:'a'},
    kuromi: {box:[[15, 17, 10, 12], [15, 17, 21, 23]], only:'a', lid:'f', line:'a'},
    cinnamoroll: {box:[[17, 19, 11, 12], [17, 19, 20, 21]], only:'d', lid:'c', line:'a'},
    mymelody: {box:[[15, 17, 9, 10], [15, 17, 20, 21]], only:'a', lid:'w', line:'a'},
    jason: {box:[[10, 13, 10, 13], [10, 13, 18, 22]], only:'b', lid:'c', line:'b'},
    chucky: {box:[[12, 13, 13, 14], [12, 13, 22, 23]], only:'a', lid:'c', line:'a'},
    bowser: null, amongus: null
  };
  function handEyes(rows, pal, spec) {
    const g = rows.map(r => [...r]), cells = (spec.cells || []).slice();
    (spec.box || []).forEach(([y0, y1, x0, x1]) => { for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) {
      const ch = g[y][x]; if (ch === '.' || (spec.only && !spec.only.includes(ch)) || (spec.except && spec.except.includes(ch))) continue; cells.push([y, x]); } });
    /* o desenho não muda (a pupila continua preta): só guarda onde fica o olho, para fechar quando pisca */
    const out = rows.slice(); out.eyes = cells; out.eyeFrom = {lid:spec.lid, line:spec.line};
    return {rows:out, pal:Object.assign({}, pal, {lid:spec.lid, o:pal[spec.line]})};
  }
  const add = (info, pal, rows) => {
    if (info.frames) rows = info.frames[0];
    if (EYES[info.id] === null) { /* sem piscar */ }
    else if (EYES[info.id]) ({rows, pal} = handEyes(rows, pal, EYES[info.id]));
    else if (!info.frameEyes && !rows.eyes && !rows.some(r => r.includes('e'))) ({rows, pal} = autoEyes(rows, pal));
    /* desenho reaproveitado (ex.: Springtrap usa o da Bonnie): o olho já veio marcado, só falta a cor dele */
    /* desenho reaproveitado com olhos marcados à mão (Springtrap usa o da Bonnie): pálpebra e risquinho nas cores dele */
    if (rows.eyes && !pal.lid) pal = Object.assign({}, pal, {lid:rows.eyeFrom.lid, o:pal.o || pal[rows.eyeFrom.line]});
    /* olho fechado vira um risquinho na cor "o"; se o desenho não tem "o", usa a cor do olho */
    if (pal.e && !pal.o) pal = Object.assign({}, pal, {o:pal.e});
    ROWS[info.id] = rows;
    Pets.addSpecial(Object.assign({price:500, group:grupoDe(info.id)}, info), {pal, rows, eyes:rows.eyes, knife:info.knife, frames:info.frames, frameEyes:info.frameEyes, frameMs:info.frameMs, sleep:info.sleep});
  };

  add({id:'freddy', ic:'🐻', name:'Freddy'},
    {d:'#916C4A', g:'#977A83', f:'#BA906B', b:'#372836', w:'#FFFFFF', h:'#CDB9C0', c:'#79535E', a:'#141414'}, [
    '......................aaaaa.......................',
    '......................abbba.......................',
    '......................abbba.......................',
    '................aaaa.aabbbaa.aaaa.................',
    '...............accccabaaaaabacccca................',
    '...............acddcaabbbbbaacddca................',
    '...............acffcacaaaaacacffca................',
    '...............acccaacccccccaaccca................',
    '................aaacccccccccccaaa.................',
    '.................accaaacccaaacca..................',
    '.................accccccccccccca..................',
    '.................accacacccacacca..................',
    '................accagwgcccgwgacca.................',
    '...............acccahhhccchhhaccca................',
    '...............accccaaaaaaaaacccca................',
    '...............accccdfcaaacfdcccca................',
    '................acadffffdffffdaca.................',
    '.................aadffffdffffdaa..................',
    '.................acaddddcddddaca..................',
    '.................acgaaaaaaaaagca..................',
    '.................acchghghghghcca..................',
    '..................accccccccccca...................',
    '................aaaacccccccccaaaa.................',
    '...............aaccaaaaaaaaaaaccaa................',
    '..............acacabbbabbbabbbacaca...............',
    '.............aaccaaabaabbbaabaaaccaa..............',
    '.............accacabbbbaaabbbbacacca..............',
    '............aaaaacabbbadddabbbacaaaaa.............',
    '...........acccaaccaaadddddaaaccaaccca............',
    '...........accccacccddfffffddcccacccca............',
    '..........acccccaccddfffffffddccaccccca...........',
    '..........aaaaaccacddfffffffddcaccaaaaa...........',
    '..........accccaaaccddfffffddccaaaccccaa..........',
    '.........accccccacacccccccccccacacccccca..........',
    '.........acccccaaccaaaaaaaaaaaccaaccccca..........',
    '.........acccccccacccccccccccccaccccccca..........',
    '.........aacccccaaacccccccccccaaacccccaa..........',
    '..........aaaaaaaccaaaaaaaaaaaccaaaaaaa...........',
    '................accccccaaacccccca.................',
    '...............acccccaca.acaccccca................',
    '...............acccccaaa.aaaccccca................',
    '................aaaaacca.accaaaaa.................',
    '................acccccca.acccccca.................',
    '................aacccca...accccaa.................',
    '...............aacaaaaca.acaaaacaa................',
    '..............acccccccca.acccccccca...............',
    '.............accccccccca.accccccccca..............',
    '.............acaccacccaa.accccaccaca..............',
    '.............acaccaccaa..aacccaccaca..............',
    '..............aaaaaaaa....aaaaaaaaa...............']);

  add({id:'bonnie', ic:'🐰', name:'Bonnie'},
    {d:'#9A76D1', g:'#A25773', f:'#D6C6ED', b:'#8255C6', w:'#FFFFFF', h:'#C67593', c:'#6B46A4', a:'#34324A'}, [
    '...................aaaaaa...aaaaaa...................',
    '..................aabbbbaa.aabbbbaa..................',
    '..................abbbbbba.abbbbbba..................',
    '..................abbbbbca.acbbbbba..................',
    '...................aaaaaaa.aaaaaaa...................',
    '....................abbbba.abbbba....................',
    '....................abddba.abddba....................',
    '....................acddca.acddca....................',
    '....................acccaaaaaccca....................',
    '.....................aaacccccaaa.....................',
    '....................acccbbbbbccca....................',
    '...................accbbbbbbbbbcca...................',
    '...................acbbbbbbbbbbbca...................',
    '...................acbcccbbbcccbca...................',
    '..................acccacabbbacaccca..................',
    '..................accadwdcbcdwdacca..................',
    '.................accbafffcccfffabcca.................',
    '.................acbbbaaaaaaaaabbbca.................',
    '.................accccdddaaadddcccca.................',
    '..................aaadddddddddddaaa..................',
    '..................acadddddddddddaca..................',
    '..................accaddddcddddacca..................',
    '...................acdaaaaaaaaadca...................',
    '...................accdfdfdfdfdcca...................',
    '....................accbbbbbbbcca....................',
    '..................aaaaccbbbbbccaaaa..................',
    '.................aaccaaaaaaaaaaaccaa.................',
    '................acacagggaghgagggacaca................',
    '...............aabbaaahaagggaahaaabbaa...............',
    '...............accacahhhaaaaahhhacacca...............',
    '..............aaaaacaghhadddahhgacaaaaa..............',
    '.............acbbaacbaaadddddaaabcaabbca.............',
    '.............acbbcacbbdddddddddbbcacbbca.............',
    '............acbbccaccdddddddddddccaccbbca............',
    '............aaaaaccacdddddddddddcaccaaaaa............',
    '...........aabbbcaaaccdddddddddccaaabbbbaa...........',
    '...........abbbbbbacacccccccccccacabbbbbba...........',
    '...........acbbbcaaccaaaaaaaaaaaccaacbbbca...........',
    '...........acccccccaccbbbbbbbbbccaccccccca...........',
    '...........aacccccaaaccbbbbbbbccaaacccccaa...........',
    '............aaaaaaaccaaaaaaaaaaaccaaaaaaa............',
    '..................accccccaaacccccca..................',
    '.................abbbbcaca.acacbbbba.................',
    '.................acbbbbaaa.aaabbbbca.................',
    '..................aaaaacca.accaaaaa..................',
    '..................acbbbbca.acbbbbca..................',
    '..................aacccca...accccaa..................',
    '.................aabaaaaca.acaaaabaa.................',
    '................accbbbbbca.acbbbbbcca................',
    '...............accbbbbbcca.accbbbbbcca...............',
    '...............acaccacccaa.aacccaccaca...............',
    '...............acaccaccaa...aaccaccaca...............',
    '................aaaaaaaa.....aaaaaaaa................']);

  add({id:'chica', ic:'🐥', name:'Chica'},
    {j:'#BE67A6', m:'#B3B2D5', b:'#A98441', w:'#FFFFFF', g:'#E48735', k:'#8B4879', n:'#CDCCE9', h:'#A49376', f:'#A45511', p:'#776443', d:'#EBD4C0', a:'#463D2E', c:'#D1BCAA'}, [
    '...................aaa..........................',
    '..................abbba.........................',
    '................aaabbbaaa.......................',
    '................abbbbbbba.......................',
    '.................abbbbba........................',
    '...............aabbbbbbbaa......................',
    '..............aabbbbbbbbbaa.....................',
    '.............aabbbbbbbbbbbaa....................',
    '.............abbbbbbbbbbbbba....................',
    '.............abbbbbbbbbbbbba....................',
    '............abbbababbbababbba...................',
    '............abbacwcbbbcwcabba...................',
    '............abbadddfffdddabba...................',
    '............abbbaaafgfaaabbba...................',
    '............abbbbbffgffbbbbba...................',
    '............abbbafffgfffabbba...................',
    '............abbaffffgffffabba......a............',
    '.............abaafffgfffaaba......aga...........',
    '..............abfaaaaaaafba.......aca...........',
    '..............aafacaaacafaa.......aaa...........',
    '............aabaafadddafaabaa.....aha...........',
    '...........aabbhaffaaaffahbbaa....ada...........',
    '..........ababahhafffffahhababa.aaahaaa.........',
    '.........aabbabahhaaaaahhababbaajjaaajjaa.......',
    '.........abbbabachhhhhhhcababajjjjjjjjjjja......',
    '........aaaaabbacccccccccabbaajjjjjjjjjjja......',
    '.......abbbaabbhhccccccchhbbajjakajjjakajja.....',
    '.......abbbbabbhhhccccchhhbbajamwmjjjmwmaja.....',
    '......abbbbbabbbhhhhhhhhhbbbajannnjjjnnnaja.....',
    '......aaaaabbabbbbbbbbbbbbbaajjaaajjjaaajja.....',
    '.....aabbbbaaabbbbbbbbbbbbbaajjjjjjjjjjjjja.....',
    '.....abbbbbbababbbbbbbbbbbabaajjjjjjjjjjja......',
    '.....abbbbbaabbaaaaaaaaaaabbabaaaddcddaaa.......',
    '.....abbbbbbbabbbbbbbbbbbbbabbaphaaaaahpa.......',
    '.....aabbbbbaaabbbbbbbbbbbaaaaaphphphphpaa......',
    '......aaaaaaabbaaaaaaaaaaabbaahahphphphahaa.....',
    '............abbbbbbaaabbbbbbahhhaaaaaaahhha.....',
    '...........abbbbbaba.ababbbbaahccccccccchaa.....',
    '...........abbbbbaaa.aaabbbbbaaaaaaaaaaaaa......',
    '............aaaaaffa.affaaaaa...................',
    '............affffffa.affffffa...................',
    '............aaffffa...affffaa...................',
    '...........aafaaaafa.afaaaafaa..................',
    '..........affffffffa.affffffffa.................',
    '.........afffafffffa.afffffafffa................',
    '.........ahfafhfffaa.aafffhfafha................',
    '.........ahfafhffaa...aaffhfafha................',
    '..........aaaaaaaa.....aaaaaaaa.................']);

  add({id:'foxy', ic:'🦊', name:'Foxy'},
    {j:'#A7993A', m:'#574242', b:'#AE7070', w:'#FFFFFF', g:'#ACA8C5', k:'#706E96', n:'#8F8BB1', h:'#C8C4E0', f:'#545376', p:'#141414', d:'#8A5B57', a:'#323446', c:'#CC8687'}, [
    '............aaaaa...........aaaaa.............',
    '............abbbba.........abbbba.............',
    '............abaabba..aaa..abbaaba.............',
    '............abccaba.abdba.abaccba.............',
    '............adccadaaaabaaaadaccda.............',
    '............addcadadbdddbdadacdda.............',
    '.............adddadbbbbbbbdaddda..............',
    '..............aaaddaadbdaaddaaa...............',
    '................aaddaadaaddda.................',
    '...............aafafadbbafadaa................',
    '............aaaadaafaaddgwgadaaaa.............',
    '............addbbaafafaahhhabbdda.............',
    '.............addbdafaddddddbbdda..............',
    '..............aadbdacccccadbdaa...............',
    '..............adddaccaaaccaddda...............',
    '...............aadacccacccadaa................',
    '.................aahcccccjaa..................',
    '..............aaaddajhghgaddaaa...............',
    '.............addaabaaaaaaabaadda..............',
    '.............adaaabgafffagbaaada..............',
    '............aaaadadbjaaahbdadaaaa.............',
    '............abbaddabbghjbbaddabba.............',
    '...........adbbaddaadbbbdaaddabbda............',
    '...........adadaddaaaaaaaabddadbda............',
    '..........abaaadabacafkfacbbadafaba...........',
    '..........abbbaaabccaaaccccbaaakaba...........',
    '..........adbbadaacccccccccaaddfada...........',
    '..........adddddaacacckfccbaaddddda...........',
    '..........adaddaamaaccaaaaamaaddda............',
    '...........aaaaaammafkkkfammaaaaaa............',
    '...........afkkfammmmmmmmmmmaffkkaa...........',
    '...........aaffaaammmmmmmmmaafkkkka...........',
    '...........affaammaaaaaaaaammafkkfa...........',
    '...........akaaammmmma.ammmmmaanfna...........',
    '...........akaafammmma.ammmmaannkna...........',
    '...........aakfaamaamp.amaama.aaaa............',
    '............aaaaaafaaa.aaafaa.................',
    '................affaa...aaffa.................',
    '................aaafa...afaaa.................',
    '.................akka...akka..................',
    '................aaffaa.aaffaa.................',
    '..............aaafaafa.afaafaaa...............',
    '.............aafkkkffa.affkkkfaa..............',
    '.............annannkfa.afknnanna..............',
    '.............annannnaa.aannnanna..............',
    '.............aaaaaaaa...aaaaaaaa..............']);

  add({id:'mario', ic:'🍄', name:'Mario'},
    {m:'#CACFEB', d:'#1D8E66', g:'#F1C196', f:'#942730', b:'#45D74B', w:'#FFFFFF', n:'#3151AC', k:'#F2D855', h:'#EA9573', c:'#D42220', j:'#277FD0', a:'#141414', e:'#141414', lid:'g'}, [
    '....aaaaaa.....',
    '...acccccca....',
    '..acccwwccca...',
    '..acfwwwwfca...',
    '..afccccccfa...',
    '.agfgeggegfga..',
    '.ahfgehhegfha..',
    '..agaggggaga...',
    '...agaaaaga....',
    '..accjccjcca...',
    '.awwjkjjkjwwa..',
    '.awmjjjjjjmwa..',
    '..aajnnnnjaa...',
    '...afaaaafa....',
    '...aa....aa....']);
  add({id:'luigi', ic:'💚', name:'Luigi'},
    {m:'#CACFEB', d:'#1D8E66', g:'#F1C196', f:'#942730', b:'#45D74B', w:'#FFFFFF', n:'#3151AC', k:'#F2D855', h:'#EA9573', c:'#D42220', j:'#277FD0', a:'#141414', e:'#141414', lid:'g'}, [
    '.....aaaaaa......',
    '....abbbbbba.....',
    '...abbbwwbbba....',
    '...abdwwwwdba....',
    '...adbbbbbbda....',
    '..agfgeggegfga...',
    '..ahfgehhegfha...',
    '...agaggggaga....',
    '....agaaaaga.....',
    '....aaggggaa.....',
    '...abbjbbjbba....',
    '..awwjkjjkjwwa...',
    '..awmjjjjjjmwa...',
    '...aajnnnnjaa....',
    '....ajjaajja.....',
    '....afa..afa.....',
    '....aa....aa.....']);

  /* Mario, Luigi, Peach, Daisy e Bowser: lidos quadradinho por quadradinho das referências que ela mandou (30/09/2026) */
  add({id:'peach', ic:'👑', name:'Peach'},
    {j:'#F99D5A', m:'#CA1083', q:'#DFDFDF', b:'#FC8B27', w:'#FFFFFF', g:'#008B8B', k:'#F1E78A', n:'#FE01FF', h:'#F91596', f:'#FC69B7', p:'#7E7E7E', d:'#20B0AD', a:'#2D2D2F', c:'#F8D30C'}, [
    '......................a.aa.a...................',
    '.....................aaaaaaaa..................',
    '.....................abaccaba..................',
    '....................addbcffcda.................',
    '....................agdbbhfbga.................',
    '.....................aaaabaaa..................',
    '....................abbcbabbaa.................',
    '...................abccccbcccba................',
    '.................aabccccccccccba...............',
    '............a...abcccccccccccccaa..............',
    '.............aaabcccccccccccccccca.............',
    '............abccccccbbccccccccccba.............',
    '.............acccccccbbbcccccbbca..............',
    '............abbccccccbaabcccbaacba.............',
    '.............abbcccccajjabbbajabba.............',
    '..............abbbbbcajkjaaajaaba..............',
    '...............aabaacakkakkkakaa...............',
    '...............abakacakkakkkakaa...............',
    '..............abcajaccakakkkakaaa..............',
    '...........aaaaccbadacakkkkkkjaba..............',
    '............accccaggdajkkaakjada...............',
    '............abcccbagabajkkkjaaga...............',
    '.............aacbaaaaabaaaaahfa................',
    '............abbbahfffhahfhccahfaa..............',
    '.............abahfffffhafcgdcaffa..............',
    '.............abahffffffafbggcahfa..............',
    '.............abahfffhhahfhbchahha..............',
    '.............abbahfhfaamhffhhaja...............',
    '..............abbaaaakkamnmmappa...............',
    '..............aabbbbajppahffaqpa...............',
    '...........aaaabbbbaappqpahfaqa................',
    '............acbbbbahhapqqqaapqa................',
    '.............acbbahfhhapqqqqapa................',
    '..............acahffffhapqqqpaha...............',
    '...............ahffffffhapqqqpaha..............',
    '...............mhhffffffhapqpaffa..............',
    '..............anmahffffffhaaahfhma.............',
    '.............amnammnnahffffhhahmma.............',
    '............amnnamnnammnnnnnmmannma............',
    '............amnnamnnamnnnnnnnmannma............',
    '............amnamnnamnnnnnnnnnmanma............',
    '...........ammnamnnamnnnnnnnnnmanma............',
    '...........amnnamnnamnnnnnnnnnmanmma...........',
    '...........ammnamnnamnnnnnnnnnmanmma...........',
    '............ammamnnamnnnnnnnnnmammma...........',
    '.............aaammmammmnnnnnnnmamaa............',
    '................aaaaaammmmmmmmaaa..............']);

  add({id:'link', ic:'🗡️', name:'Link'},
    {d:'#EBD0A5', g:'#AF5A36', f:'#BBD173', b:'#649F63', w:'#FFFFFF', c:'#EBD85F', a:'#141414'}, [
    '.........aaaaaa.........',
    '........aabbbbaa........',
    '.......aabbbbbbaa.......',
    '......aabbbbbbbbaa......',
    '......abaccccccaba......',
    '......aaccccccccaa......',
    '.....aaccaccccaccaa.....',
    '...aaaacaccccaaacaaaa...',
    '...addaaccccaadacadda...',
    '....aaaaccaaaddacaaa....',
    '.....acaaaaadaaaaca.....',
    '.....acawaaddaawaca.....',
    '.....aaadawddwadaaa.....',
    '......aaaddddddaaa......',
    '.......aaaaaaaaaa.......',
    '......afabbbbbbafa......',
    '.....affabbbbbbaffa.....',
    '....addaabbbbbbaadda....',
    '....aadabaaccaabadaa....',
    '.....aaabbaccabbaaa.....',
    '.......aaabbbbaaa.......',
    '......agggaaaaggga......',
    '......aggaa..aagga......',
    '.......aaa....aaa.......']);

  add({id:'yoshi', ic:'🦖', name:'Yoshi'},
    {k:'#111111', g:'#34A855', d:'#37761D', w:'#FFFFFF', e:'#111111', r:'#CC0000', l:'#92C47D', p:'#F3CDCC', n:'#B45F05', q:'#E88F37', lid:'w'}, [
    '.........kk.kk......',
    '........kdgkggk.....',
    '.......kdgwwwwgk....',
    '.....kkkdwwewewk....',
    '....krrkgwwewewk....',
    '....kkrkgwwwwwwkk...',
    '...krrkdggwwgwgggk..',
    '...krkdgggggggkgkgk.',
    '....krdggwwgggggggk.',
    '.....kkdwwwwkgggggk.',
    '......kkwwwkkkgggk..',
    '.....kpkkwwwwkkkk...',
    '.....rkkgglwk.......',
    '.kgdkkggkllwkdk.....',
    '..kgdkgggkwwkdk.....',
    '...kwgkggkwwkk......',
    '....kwwkkwwk........',
    '.....knnklk.........',
    '.....kqqqkqk........',
    '......kkkkk.........']);


  add({id:'hollow', ic:'🗡️', name:'Hollow Knight'},
    {d:'#B0ABAA', g:'#585452', f:'#867E7A', b:'#F4F1F2', w:'#141414', h:'#726C69', c:'#D5D0D0', j:'#18181A', a:'#141414', k:'#3E3E52', l:'#56566E'}, [
    '...............aaa...........aaa...............',
    '.............aabbba.........abbbaa.............',
    '............abbbaa...........aabbba............',
    '...........abbbbba...........abbbbba...........',
    '..........abbbaaaa...........aaaabbba..........',
    '.........abbba...................abbba.........',
    '........abbba.....................abbba........',
    '........abbba.....................abbba........',
    '........abbba.....................abbba........',
    '........abbba.....................abbba........',
    '........abbbba...................abbbba........',
    '........abbbba.aaaaaaaaaaaaaaaaa.abbbba........',
    '.........abbbbabbbbbbbbbbbbbbbbaabbbba.........',
    '.........abbbbbbbbbbbbbbbbbbbbbbbbbbba.........',
    '..........abbbbbbbbbbbbbbbbbbbbbbbbba..........',
    '...........abbbbaaabbbbbbbaaabbbbbba...........',
    '............abbaaaaabbbbbaaaaabbbba............',
    '............abbaaaaabbbbbaaaaabbbaa............',
    '............abbaaaaabbbbbaaaaabbbba............',
    '............abbaaaaabbbbbaaaaabbbba............',
    '............abbaaaaabbbbbaaaaabbbba............',
    '............abbbaaabbbbbbbaaabbbbba............',
    '............abbbbbbbbbbbbbbbbbbbbba............',
    '............acbbbbbbbbbbbbbbbbbbbca............',
    '............adcbbbbbbbbbbbbbbbbbcda............',
    '...........aaadcbbbbbbbbbbbbbbbcda.............',
    '..........afaaddcccccccccccccccdda.............',
    '...........ghaaddddddddddddddddda..............',
    '...........aghhaadddddddddddddaa...............',
    '...............akkklkkkklkkklkka...............',
    '...............akkklkkkklkkkkkka...............',
    '...............akkklkkkkkkkklkka...............',
    '..............akkkkkkkkklkkklkkka..............',
    '..............akkkklkkkklkkklkkka..............',
    '..............akkkklkkkklkkkkkkka..............',
    '.............akkkkklkkkkkkkklkkkka.............',
    '.............akkkkkkkkkklkkklkkkka.............',
    '.............akkkkklkkkklkkklkkkka.............',
    '............akkkkkklkkkklkkkkkkkkka............',
    '............akkkkkklkkkkkkkklkkkkka............',
    '............akkkkkkkkkkklkkklkkkkka............',
    '...........akkkkkkklkkkklkkklkkkkkka...........',
    '...........akkkkkkklkkkklkkkkkkkkkka...........',
    '...........akkkkkkklkkkkkkkklkkkkkka...........',
    '...............aaaaaaaaaaaaaaaaa...............',
    '....................aa...aa....................',
    '....................aa...aa....................']);

  add({id:'pikachu', ic:'⚡', name:'Pikachu'},
    {j:'#FEF6A6', m:'#E89688', b:'#54535B', w:'#FFFFFF', g:'#F5C018', k:'#040305', n:'#E15943', h:'#DB8F00', f:'#F6E853', p:'#C52018', d:'#A05306', a:'#272727', c:'#633009'}, [
    '.............................................',
    '.................aa.......................aaa',
    '.................abaa...................aabaa',
    '.................abbaa.................cbbbaa',
    '.................abbbad...............afbbaa.',
    '.................aabfgd..............dffbaaa.',
    '..................ahffgd............dgfffaa..',
    '..................affffd............dffffaa..',
    '..................cgfffgd..........dffffga...',
    '.....dd............cfffgd.dddddd...dfffga....',
    '....dffd...........cgffddhjjjjffhddffffc.....',
    '...dffffd...........cgdjjjjjjjjfffgfffc......',
    '...dfffffh...........dffjjjjjffffffffc.......',
    '..dfffffffh.........dhkgffffffgkkgffdc.......',
    '.dfffffffffh........dkwkffffffbwkaffgc.......',
    '.dffffffffffd......dfakaffffffkkbaffgd.......',
    'dffffffffffffd.....cfgagfchfffgaagfgghc......',
    'dffffffffffffd.....amfffffffffffffnpggk......',
    'kfffffffffffggd....anffhdaaddffffnnppgk......',
    '.kkfffffffffgggd...anfffgappgffffnnppgk......',
    '...kkffffffgggggd...affffpnpfffffnpppgk......',
    '.....kkfffggggggk...afffffngfffffgpphgc......',
    '.......kkggggggk.....affffffffffgggggghc.....',
    '.........kkgggck.....cffffffffgggggggggk.....',
    '...........dggc......dffgggggggggggggggk.....',
    '..........cggk......dffffgggggggggghfggk.....',
    '..........cgghk.....cffffffhgggggghfffgk.....',
    '.........cgggghk....cfffffffhgggggdfffgk.....',
    '.........kchghhhc..cffgfffffdggggdfffghk.....',
    '...........cchhhc..cffhgffffgkggdgffggdk.....',
    '.............khc..dffffdgffffjcgddgggcgd.....',
    '.............kdk.cffffffddgffkgggkgkkgghd....',
    '............kdddcdffffffffdckggggkkgggggk....',
    '............kdddcfffffffffffggggggggggggk....',
    '.............kkdkfffffffffggggggggggggggk....',
    '...............kkfffffffffgggggggggggggkk....',
    '................cgfffffffggggggggggggggk.....',
    '.................cgffffgggghhhhhggggggk......',
    '.................khggggggghhhhhhhhgghk.......',
    '..................khgggggckkkcdddhhdkc.......',
    '...................kdhhddc.....khhhgggc......',
    '..................cgffghc.......kkchgdgc.....',
    '.................cfffgkk...........ckkk......',
    '.................khdhkk......................',
    '..................kkk........................']);

  add({id:'kirby', ic:'🩷', name:'Kirby'},
    {d:'#FD68B1', g:'#67031E', f:'#FDA5D0', b:'#DC026E', w:'#FFFFFF', h:'#9E0010', c:'#F732A6', a:'#201F1D'}, [
    '....................',
    '....................',
    '....................',
    '....................',
    '.......aaaaaa.......',
    '.....aaabccbaaa.....',
    '....aacdffffcgaa....',
    '...aadffffffffdga...',
    '...adffffbcfbcfda...',
    '..aafffffwgfwgffba..',
    '.aadfffffbafcaffca..',
    '.acfccfffcafdaffdaa.',
    'agfghhgbbdaffabdghha',
    'afchbwbgffffffdghbba',
    'adgbbbbhcfffbfcgbbba',
    'abgbbbbbcfffffchbbba',
    '.aabbbbbgfffffgbbbha',
    '..ahbbbbgcdddcgbbba.',
    '...ahbbhacccccahhha.',
    '....aaaaaaaaaaaaaa..']);

  add({id:'puppet', ic:'🎭', name:'Puppet'},
    {d:'#E2E2E0', f:'#E2ABAB', b:'#FD0000', w:'#FFFFFF', c:'#8A2BE3', a:'#010727'}, [
    '..........aaaaa..........',
    '.........awwwwwa.........',
    '........awwwwwwwa........',
    '........awwwwwwwwa.......',
    '.......awwwawwwawa.......',
    '.......awwaaawaaaa.......',
    '.......awbwcwwwcwa.......',
    '.......awwaaaaaawa.......',
    '........awwaaaawa........',
    '.........awwwbwa.........',
    '..........aaaaa..........',
    '...........aaa...........',
    '.........aaaaaaa.........',
    '........aaaawaaaa........',
    '.......aaaaaaaaaaa.......',
    '......awaaaawaaaawa......',
    '.....aaaawaaaaawaaaa.....',
    '.....awawwaawaawwawa.....',
    '.....aaaawaaaaawaaaa.....',
    '.....aaaawaaaaawaaaa.....',
    '......aawawaaawawaa......',
    '........aaawawaaa........',
    '......aaawaa.aawaaa......',
    '.....aawaaa...aaawaa.....',
    '.....aaaaaa...aaaaaa.....']);

  add({id:'bowser', ic:'🐢', name:'Bowser'},
    {d:'#FEB042', g:'#58585A', f:'#0A9442', b:'#EF5A2A', w:'#FFFFFF', c:'#A0D06F', a:'#141414'}, [
    '...................a...a.................',
    '..................awa.awa................',
    '..................awwabbwa...............',
    '...............aa.awwwaabbaaa............',
    '..............awaaaawwwwaaabba...........',
    '...............awbbawwwwwabbbbaa.........',
    '................abwbawwwaccaabbba........',
    '..............aawwbbbaaacccawwaa.........',
    '.............abwbbbbaccccccawwwaaaa......',
    '............awbbbbbbaccccccawwaaddda.....',
    '............awawwwbaccccccccawadddada....',
    '.............aawbbbacccccccccadddddda....',
    '.............awwbbwaccccaddddddddddda....',
    '............awbbbwaacccaddddddddddwa.....',
    '............ababbaaaaccadddddddwwawa.....',
    '.............awaaawwwaaadddwwaawwaa......',
    '........aaaaaawwffaawwwaaddaaawaa........',
    '........awwwffffffffawwwaaddddaa.........',
    '........awwwffffffwffawwaaaadddda........',
    '........awwfffffffwwffawwa..aaaa.........',
    '........affffwwwffffffawwaa..............',
    '........affffwwwffffffawwada.............',
    '.......awffffwwfffffaawwadda.............',
    '......awwffffffffffawwwwagwa.............',
    '.......affffffffffaawwwaggga...aaa.......',
    '.......afffffffwwfawwwagwgadaaaddwa......',
    '.......affwwwffwffawwwaggaddddddda.......',
    '......awffwwwffffaawwagggaddddddda.......',
    '.......affwwfffffawwwagwaddddddddda......',
    '.......affffffffaawwwaggadddddddddwa.....',
    '........affffffaawwwaaaaaadddddddaa......',
    '.........afffaawwwwwadaddaaaadddwa.......',
    '........awaaawwwwwwadddaa....aaaa........',
    '.......aawwwwwwwwwaadddda................',
    '......awaawwwwwwaadddddda................',
    '.....aawwaaaaaaadddddddda................',
    '....awaaaddddddaaddddddaa................',
    '....aaddddddddaaaddddddddaa..............',
    '...adddddddaaa.adddddddddwwa.............',
    '....aaaaaaa....adddddddddwwwa............',
    '................aaaaaaaaaaaa.............']);

  /* ---------- outros jogos ---------- */
  add({id:'sonic', ic:'💨', name:'Sonic'},
    {c:'#FAC192', w:'#FFFFFF', a:'#141414', d:'#FE0000', b:'#0170C1'}, [
    '....aaaaaaaaaaaa...aa....',
    '...abbbbbbbbbbbbaaaba....',
    '....abbbacbbbbbbbbbba....',
    '.....abbaccbbbbbbbbba....',
    '......abacbbbbbbbbbbba...',
    '.....abbbbbbbbwwwbbbba...',
    '....abbbbbbbbwwwwwbbba...',
    '...abbbbbbbbbwwwwabwa....',
    '..aaaaaabbbbbwwwwabwa....',
    '......abbbbbbbwwwawaaa...',
    '.....abbbbbcccwwwwcca....',
    '....abbbbbbccccccccca....',
    '...aaaaaaaaaccccccca.....',
    '..........acaaaaaaaa.....',
    '.........acaabcccaaaa....',
    '........acawwacccawwa....',
    '........aawwwwaccawwa....',
    '.........awwwwaacawa.....',
    '..........awwaabaaaa.....',
    '...........aabaaa........',
    '...........aabaddaa......',
    '..........aaddaaddwaa....',
    '..........adddwdaaddda...',
    '..........addwddddaddda..',
    '..........aaaaaaaaaaaaa..']);
  /* Tails voando (GIF de 2 quadros: as caudas giram e o corpo sobe e desce); dormindo fica no 1º quadro de olho fechado */
  add({id:'tails', ic:'🦊', name:'Tails', frameMs:120,
      sleep:{pal:{d:'#646D76', g:'#2A2B2A', f:'#AAACA9', b:'#FF7000', w:'#FFFFFF', h:'#8B0101', c:'#E89F04', j:'#FE0000', a:'#8D440F'}, rows:[
        '...............................',
        '...............................',
        '...........abcaaa.......aaa....',
        '...........abdccbaaaaaaaaaaabcc',
        '...........abfddccabbbcbbbab...',
        '...........abbwffabbcccccbbcc..',
        '...........aabwwabbcccccccabwcc',
        '............aabwbbcccccccccab..',
        '............aaabbcccbwwwbcwawb.',
        '......d.f..waabbbccbwwwwwbwa...',
        '........d..faabbbccbwwwwwbwa...',
        '.ddd..w.wdfwaabbbbcbwggggbgg...',
        '...dddw.wwdfwaabbdfdbwwwwww....',
        '.....dd.wwdfwaaaadwwwwwwwwwwgg.',
        '.....dddwwdfwfaddfwwwwwwwwwwd..',
        '....ddddwdfwwwaaadfwwwwwwwdd...',
        '...dddddwdfwwaaaddddffffdd.....',
        '...ddddddffwaafwwaaadddd.......',
        '..ddddddffwwwwfwaabadfffd......',
        '.ddddddffwwwwwfaabcdfwwwfd.....',
        'dadddaabbcwcwwaaacafwwwwwd.....',
        'aaaadabbcccccbdddabfwwwwfd.....',
        'aaaaabbbcccccdddfdadwwwwfdd....',
        'aaaaabbcccccdddfwwddffffdfdd...',
        'aaaaabbbccccddffdwdbbbbddwdd...',
        'aaaaabbbccccddfddfabcgddddd....',
        'aaaaabbbbbcccdddwghbcggh.......',
        '.aaaaabbbbbbbbawgdfwwghhdd.....',
        '..aaaaabbbbbaaagdddfwggghhhh...',
        '....aaaaaaaaa.ghhhjjjjj.ffdddd.',
        '........aaaa..ghjjjjjj....ffddd']},
      frameEyes:[[[13, 21], [13, 22], [14, 21]], [[14, 21], [14, 22], [15, 21]]],
      frames:[[
      '......................................',
      '..............aaaaaaa.................',
      '..........aa..wwwwwww.aaa.............',
      '.......aa.waaaawwwwww.wwwa............',
      '....aa.ww.wwaaaaaaaaaaaaaaaa..........',
      '..aaaw.wwaabbbbbbbbb..................',
      '.aaaaaaabbbbbbbbwwwwwwwwwwwwaac.......',
      'aaaaabbbbbbbbbbbdfwwwwwwwwwwwaac......',
      'aa....wwwbbbbbbbdfffdffddwwaaaac......',
      'a.....wwwwwwwwbbdfffwwaaddddaac.......',
      '..............bbfggdbdwwwcccac........',
      '..............bbgaadbbbdwwcccwww..f...',
      '..........hhhhbbgaafbhbbdwwwwwwwffg...',
      '......hhhhhhhhfbdwwfbaabbdwwwwwfggg...',
      '..............fbdwwfbawcbbgfddgfggg...',
      '..............gbdbdgbwwabbfbbbbdfgg...',
      '.............gfbbbbgdwabbbbbbbbbdfbbbb',
      '.............gfbbbbgdbbbbbbbbbbbbbf...',
      '............gfdbbbbgfbbbbbbbbbbbbfbbb.',
      '............gfbbbbbgfdbbbbbbbbbbbbfwwb',
      '............gdbdbbbffdbbbbbwwbbbaddb..',
      '.........jjjgbbfdfbgfdbbbbwwwwbbabwwb.',
      '........jghkdbdggfbggddbbbwwajbbjd....',
      '.......jgcjfbbfgggdbgfcaabwwakbbkd....',
      '.......jgajdbgwjjjdbgggcwabwcjbbjm....',
      '.......jghwggwjkjjgbghcawwwwwwwwwajk..',
      '.......jffhckwkjjjgbbgghwwwwwwwwwwac..',
      '.......jfbffwwkjgjgdbfkcaawwwcwaac....',
      '.......kfbffwjjkhcwgdfkwkhcaaacc......',
      '.......kwff.wjjjjjwkhchhw..wggg.......',
      '.......kwwa.wjjjjjhcawwah..khcch......',
      '.......kwaa.wjjgjjhaawcak..hahaah.....',
      '.......kwac.wjkgg.kcaawck..hchawh.....',
      '.......kah..jhhhk..kcaak...khaack.....',
      '.......hh...jhcc....khh.....khck......',
      '............jhch......................',
      '............jkh.......................',
      '......................................'],
    [
      '......................................',
      '......................................',
      '......................................',
      '.................aa...aaa.............',
      '.......aa........ww..awww.aa..........',
      '.......................aw.ww.a........',
      '...a...ww........ww..wwbbbwwawa.......',
      '..aaa..ww........wwbbbbbbbbbaawc......',
      '.aaabb.ww.......bbbbbbbbdddddaac......',
      '.aawwbbbb....bbbbbbbwwdfffffwcac......',
      'aaabbbbbbbbbbbbdbbdbwwwwwwwccac.......',
      'acabbbbbbbbbbbfdbdfdbdwwwccccc........',
      '.acccbbbbdddwwfdbfwdbbbdwwwwwwww..f...',
      '...cccchhhwwwwfdbfwfbhbbdwwwwwwwfgg...',
      '......hchhhhhhfdbdwfbaabbdwwwwwfggg...',
      '............hafdbdwfbawcbbgfddgfggg...',
      '..............gbbbdgbwwabbfbbbbdffd.bb',
      '.............gfbbbbgdwabbbbbbbbbddbb..',
      '.............gfbbbbgdbbbbbbbbbbbbdf...',
      '............gfdbbbbgdbbbbbbbbbbbbfbbbb',
      '............gfbbbbbgfbbbbbbbbbbbbbf...',
      '............gdbdbbbffdbbbbbwwbbbaddbb.',
      '.........jjjgbbfdfbgfdbbbbwwwwbbab....',
      '........jgckdbdgggdggddbbbwwajbbjd....',
      '.......jgajfbbfgggdbgfcaabwwakbbkd....',
      '.......jgajdbgwjjjdbgggcwabwcjbbjm....',
      '.......jgcwggwjkjjgbghawwwwwwwwwwajk..',
      '.......jffhckwkjjjgbbgghwwwwwwwwwwac..',
      '.......jfbffwwkjgjgdbfkcawwwacwaaa....',
      '.......kfbffwjjkhcwgdfkwkhcaaacc......',
      '.......kwff.wjjjjjwkhchhw..wggg.......',
      '.......kwaa.wjjjjjhcawwah..khcch......',
      '.......kwaa.wjjgjjhaawcak..hahaah.....',
      '.......kaac.wjkgg.kcaawck..hchawh.....',
      '.......kah..jhhck..kcaak...khaack.....',
      '.......hh...jhcc....khh.....khck......',
      '............jhch......................',
      '............jkh.......................']]},
    {m:'#CE843A', d:'#C84906', g:'#8D0902', f:'#B91E07', b:'#E08607', w:'#FFFFFF', k:'#454058', h:'#526181', c:'#7E9BAB', j:'#141414', a:'#ACCBCE', lid:'w', o:'#141414'}, null);
  add({id:'pacman', ic:'🟡', name:'Pac-Man'},
    {w:'#FFFFFF', a:'#141414', b:'#FFED5D'}, [
    '........aaaaaa........',
    '......aabbbbbbaa......',
    '....aabbbbbbbbbbaa....',
    '...abbbbbbbbbbbbbba...',
    '..abbbbbbbbawbbbbbba..',
    '..abbbbbbbaawwbbbbba..',
    '.abbbbbbbbaaaabbbbbba.',
    '.abbbbbbbbaaaabbbbbba.',
    'abbbbbbbbbbaabbbbbaa..',
    'abbbbbbbbbbbbbbbaa....',
    'abbbbbbbbbbbbbaa......',
    'abbbbbbbbbbbaa........',
    'abbbbbbbbbaa..........',
    'abbbbbbbbbbaa.........',
    '.abbbbbbbbbbbaa.......',
    '.abbbbbbbbbbbbbaa.....',
    '..abbbbbbbbbbbbbbaa...',
    '..abbbbbbbbbbbbbbbba..',
    '...abbbbbbbbbbbbbba...',
    '....aabbbbbbbbbbaa....',
    '......aabbbbbbaa......',
    '........aaaaaa........']);
  add({id:'creeper', ic:'💥', name:'Creeper'},
    {g:'#5CB85C', d:'#3A8A3A', l:'#8FD88F', k:'#1E1B1A'}, [
    '...gglgdgglgg...',
    '...gdggggdggl...',
    '...gkkggggkkg...',
    '...gkkggggkkg...',
    '...ggggkkgggg...',
    '...gggkkkkggg...',
    '...gggkkkkggg...',
    '...gggkggkggg...',
    '....gdgglgdg....',
    '....gglggdgg....',
    '....gdgglggg....',
    '....ggdggglg....',
    '....glggdggd....',
    '...gdgg..gdgg...',
    '...ggdg..ggdg...',
    '................']);
  add({id:'steve', ic:'⛏️', name:'Steve'},
    {o:'#2A1A10', h:'#4A2E1A', s:'#C98A5A', w:'#FFFFFF', e:'#4A3AA8', m:'#7A4A30', t:'#3AB0B8', b:'#3A3AA8', k:'#6A6A6A', lid:'s'}, [
    '....hhhhhhhh....',
    '....hhhhhhhh....',
    '....hssssssh....',
    '....ssssssss....',
    '....swesswes....',
    '....sssmmsss....',
    '....ssmmmmss....',
    '....ssssssss....',
    '..tttttttttttt..',
    '..tttttttttttt..',
    '..ss' + 'tttttttt' + 'ss..',
    '..ss' + 'tttttttt' + 'ss..',
    '....bbbbbbbb....',
    '....bbbbbbbb....',
    '....bbbbbbbb....',
    '....kkkkkkkk....']);
  add({id:'amongus', ic:'🚀', name:'Among Us'},
    {d:'#4A6369', f:'#740A38', b:'#BD1704', w:'#FFFFFF', c:'#96C8D9', a:'#141414'}, [
    '............aaaaaaaaaa.........',
    '...........aabbbbbbbbaa........',
    '..........aabbbbbbbbbbaa.......',
    '..........abbbbbbbbbbbbaa......',
    '.........aabbbbbbbbbbbbba......',
    '.........abbbbbaaaaaaaaaaa.....',
    '.........abbbbaaccccwwwccaa....',
    '.........abbbbadcccwwwcccca....',
    '......aaaabbbbaddccccccccca....',
    '.....aabbabbbbadddcccccccca....',
    '....aabbbabbbbaddddddddddda....',
    '....afbbbabbbbaadddddddddaa....',
    '....affbbabbbbbaaddddddaaa.....',
    '....affffabbbbbbaaaaaaaaba.....',
    '....affffafbbbbbbbbbbbbbba.....',
    '....affffaffbbbbbbbbbbbbba.....',
    '....affffaffbbbbbbbbbbbbfa.....',
    '....affffafffbbbbbbbbbbbfa.....',
    '....affffafffbbbbbbbbbbbfa.....',
    '....affffaffffbbbbbbbbbbfa.....',
    '....affffafffffffbbbbbfffa.....',
    '....affffafffffffffffffffa.....',
    '....aafffafffffffffffffffa.....',
    '.....aaaaaffffffffffffaffa.....',
    '.........affffffaaaaaafffa.....',
    '.........affffffa..afffffa.....',
    '.........affffffa..afffffa.....',
    '.........affffffa..affffaa.....',
    '.........affffffa..aaffaa......',
    '.........aaffffaa...aaaa.......',
    '..........aaaaaa...............']);
  add({id:'sans', ic:'💀', name:'Sans'},
    {c:'#4296F0', w:'#FFFFFF', a:'#141414', b:'#366BA1'}, [
    '..........aaaaaaaaa...........',
    '........aawwwwwwwwwaa.........',
    '.......awwwwwwwwwwwwwa........',
    '.......awwwwwwwwwwwwwa........',
    '......awwwwwwwwwwwwwwwa.......',
    '......awwaaawwwwwaaawwa.......',
    '......awwaaawwwwwaaawwa.......',
    '......awwaaawwawwaaawwa.......',
    '.......awwwwwaaawwwwwa........',
    '......aawawwwwwwwwwawaa.......',
    '......awwaaaaaaaaaaawwa.......',
    '......awwwawawawawawwwa.......',
    '.......aawwaaaaaaawwaa........',
    '......aaaaawwwwwwwaaaaa.......',
    '.....abaaaaaaaaaaaaaaaba......',
    '....aabaccawwwawwwaccabaa.....',
    '....abbbaccaaawaaaccabbba.....',
    '...abbaabaaawwawwaaabaabba....',
    '...abbbbabbawwwwwabbabbbba....',
    '...abbbbbabaawwwaababbbbba....',
    '....abbbabbawwwwwabbabbba.....',
    '.....aababbaaaaaaabbabaa......',
    '......aaabbaaaaaaabbaaa.......',
    '......aaaaaaaaaaaaaaaaa.......',
    '.....aaaaaaaaaaaaaaaaaaa......',
    '.....aaaaaaaaa.aaaaaaaaa......',
    '......aaaaaaa...aaaaaaa.......',
    '....aaawwwwwa...awwwwwaaa.....',
    '....awwwwwwaa...aawwwwwwa.....',
    '.....aaaaaa.......aaaaaa......']);

  /* ---------- mais FNAF (reaproveitam o desenho dos originais com outras cores) ---------- */
  add({id:'goldenfreddy', ic:'🌟', name:'Golden Freddy'},
    {c:'#AF9E62', w:'#FFFFFF', a:'#373428', d:'#E2D4A4', b:'#8B731D'}, [
    '....................aaaaa....................',
    '....................aaaaa....................',
    '....................aaaaa....................',
    '..............aaaa.aaaaaaa.aaaa..............',
    '.............abbbbaaaaaaaaabbbba.............',
    '.............abccbaaaaaaaaabccba.............',
    '.............abccbabaaaaababccba.............',
    '.............abbbaabbbbbbbaabbba.............',
    '..............aaabbbbbbbbbbbaaa..............',
    '...............abbaaabbbaaabba...............',
    '...............abbbbbbbbbbbbba...............',
    '...............abbaaabbbaaabba...............',
    '..............abbaawaabaawaabba..............',
    '.............abbbaaaaabaaaaabbba.............',
    '.............abbbbaaaaaaaaabbbba.............',
    '.............abbbbcccaaacccbbbba.............',
    '..............abacccccccccccaba..............',
    '...............aacccccccccccaa...............',
    '...............aaaccccbccccaaa...............',
    '...............abaaaaaaaaaaaba...............',
    '...............abcaaaaaaaaacba...............',
    '..............aabbdcddcddcdbbaa..............',
    '.............aababbbbbbbbbbbabaa.............',
    '............ababaabbbbbbbbbaababa............',
    '...........aabbabaaaaaaaaaaababbaa...........',
    '...........abbabaaaaaaaaaaaaababba...........',
    '..........aaaaabaaaaaaaaaaaaabaaaaa..........',
    '.........abbbaabaaaaacccaaaaabaabbba.........',
    '.........abbbbabbaaacccccaaabbabbbba.........',
    '.......aaaaabbabbcccccccccccbbabbaaaaa.......',
    '......aabbbbabbabcccccccccccbabbabbbbaa......',
    '......abbbbbbaaaaacccccccccaaaaabbbbbba......',
    '......abbbbbaabbbbabbbbbbbabbbbaabbbbba......',
    '......abbbbbabbbbbbaaaaaaabbbbbbabbbbba......',
    '......aabbbbabbbbbbabbbbbabbbbbbabbbbaa......',
    '.......aaaaabbbbbababbbbbababbbbbaaaaa.......',
    '...........abbbbbaaaaaaaaaaabbbbba...........',
    '............aaaaabbba...abbbaaaaa............',
    '.............abbbbbba...abbbbbba.............',
    '.............aabbbba.....abbbbaa.............',
    '............aabaaaaba...abaaaabaa............',
    '...........abbbbbbbba...abbbbbbbba...........',
    '..........abbbbbbbbba...abbbbbbbbba..........',
    '..........ababbabbbaa...aabbbabbaba..........',
    '..........ababbabbba.....abbbabbaba..........']);
  add({id:'springtrap', ic:'🐇', name:'Springtrap'},
    {a:'#1E1E10', b:'#8A8A4A', c:'#5E5E2E', d:'#B8B87A', f:'#E8E0A0', g:'#4A4A22', h:'#6A6A3A', w:'#F0ECD0'}, ROWS.bonnie);
  add({id:'mangle', ic:'🦊', name:'Mangle'},
    {m:'#E06666', d:'#FF0000', g:'#FFFF00', f:'#141414', b:'#FFFFFF', w:'#FF3659', k:'#FF92A5', h:'#F6B26B', c:'#CC0000', j:'#F4CCCC', a:'#666666'}, [
    '..aaaaaa...........aaaaaa...',
    '..abbbbbaa.......aabbbbba...',
    '..abccccbba.....abbccccba...',
    '..abcccddba.....abddcccba...',
    '..abccdddbaaaaaaabdddccba...',
    '..abbdddbbbbbbbbbbbdddbba...',
    '...aabbbbbbbbbbbbbbbbbaa....',
    '.....abbbbbbbbbbbbbbba......',
    '......abbbbbbbbbbbbba.......',
    '......abbffbbbbbffbba.......',
    '......abfgbfbbbffbfba.......',
    '......abfhgfbbbffffba.......',
    '..aaaaabfbbfbbbffffbaaaaa...',
    '...abbjcbbkkfffkkbbcjbba....',
    '....abcdbkkkkkkkkkbdcba.....',
    '.....aaabbkkkkkkkbbaaa......',
    '.......aabbkmmmkbbaa........',
    '......abaaaaaaaaaaaba.......',
    '......abbbkabbbakbbba.......',
    '......abbkkkakakkkbba.......',
    '......aabkkkakakkkbaa.......',
    '.......abbkakkkakbba........',
    '.......aaaaakkkaaaaa........',
    '......abbbbakkkabbbba.......',
    '......abbkbaaaaabkbba.......',
    '......abkkka...akkkba.......',
    '.......akkka...akkka........',
    '........aaa.....aaa.........']);
  add({id:'balloonboy', ic:'🎈', name:'Balloon Boy'},
    {j:'#3060B2', m:'#143091', q:'#1799CA', b:'#F6B913', s:'#262626', w:'#FFFFFF', r:'#6E3324', g:'#F9B73B', k:'#F00404', t:'#A94200', n:'#FDA865', h:'#999489', f:'#C32C16', p:'#FEF5CC', d:'#FF5021', a:'#141414', c:'#D50131'}, [
    '................aaaaaa.......................................................',
    '.............aaabbbbbbaa.....................................................',
    '............acccbbbbbbbbaa...................................................',
    '...........acccccbbbbbbbbba..................................................',
    '..........accccccccbbbbbbbba.................................................',
    '.........accccccccccbbbbbbbba................................................',
    '........acccccccccccccbbbbbbba...............................................',
    '.......accccccccccccccccbbbbbba..............................................',
    '.......abccccccccccccccccbbbbba..............................................',
    '......abbbccccccccccccccccbbbba..............................................',
    '......abbbbcccccccccccccccccbbba.............................................',
    '......abbbbbcccccccccccccccccbba.............................................',
    '......abbbbbbccccccccccccccccbba.............................................',
    '......abbbbbbbbcccccccccccccccba.............................................',
    '......abbbbbbbbbccccccccccccccca.dddd.....dd.................................',
    '......abbbbbbbbbbbccccccccccccca.ffffddgdfffdd...............................',
    '.......abbbbbbbbbbbbcccccccccca.....dfffffffffd..............................',
    '........abbbbbbbbbbbbccccccccca...fffddhffdddd...............................',
    '........abbbbbbbbbbbbbccccccca.........h.fff.................................',
    '.........abbbbbbbbbbbbbccccca..........h.....................................',
    '..........abbbbbbbbbbbbbcccca......aaaddddaaa................................',
    '...........abbbbbbbbbbbbbcca.....aajfkmjmjfkmaa..............................',
    '............abbbbbbbbbbbbaa.....afjfkfjjmjmkkmma.............................',
    '.............abbbbbbbbbba......afjmfkmjjmjmkkfjfa............................',
    '..............aabbbbbbba.......afjmfkmjjmjjfkfjmka...........................',
    '................abbbbaa........aaaaaaaaaaaaaaaaaaa...........................',
    '.................abba.........afffnnnnnnnnnnnnnffa...........................',
    '..................aa..........affnnffffnnnffffnnfa...........................',
    '...................h..........affnfppppfnfppppfnffa..........................',
    '...................h..........affnppqqppnpqqpppnffa..........................',
    '...................h..........affnpqaaqpnqaaqppnffa..........................',
    '...................h..........affnpqaaqpnqaaqppnffa.........pp...............',
    '...................h..........affnnpqqpnfnqqppnnffa.........rr...............',
    '...................h..........affddnnnnfffnnnnddfawpppppppppppppppppppp......',
    '...................h...........afddnnnnfffnnnnddfawpaapppapapppppppppap......',
    '...................h...........afddnnnnnnnnnnnddawwpapappapapppppppppap......',
    '...................h............annnaapapapaannawwwpaappaapapapapapaaap......',
    '...................h.............annnaaaaaaannnawwwpapaaaapaaaaaaapappp......',
    '..................aha.............annnpapapnnnawwwwpaapaaapaapaaapaapap......',
    '.................annna.............aannnnnnnaawwwwwpppppppppppppppppppp......',
    '................annnnna..............ahhhhhawwwwwwwwwwwwwwwwrr...............',
    '................annnnna............aaaaaaaaaaawwwwwwwwwwwwwwrr...............',
    '................annnnna...........afmmfmjmfkjfaaaaaaawwwwwwwaa...............',
    '.................annnnna.........afmmffmjsmkfjfjjjjjjaaaaaaanna..............',
    '..................ahnnnnaaaaaaaaaffjfkfjsssfkmjfkkkkkkannnnnnnna.............',
    '...................hannnnnakkkkkkfmmfkmjsssmkfjmfjjjjjannnnnnnna.............',
    '.....................annnnajjjjjfmjmkfmjjsjjfkmjfjjjjjannnnnnnna.............',
    '......................annnajjjjffmjfkfmjsssjfkfjmfkkkkaaaaaanna..............',
    '.......................annakkkkffjmfkfmjsssjfkkmmfaaaa......aa...............',
    '........................aaaaaaafmjmfkfmjjsjjmkkmjfa.........rr...............',
    '..............................afmjmfkfmjjmjjmkkmjfa.........rr...............',
    '..............................afmjmfkfmjjmjjmkkmjfa.........rr...............',
    '.............................affmjmfkfmjjmjjmkkmjma.........rr...............',
    '.............................ammmjmfkfmjjmjjmkmmmma..........................',
    '.............................ammmmmmmmmmmmmmmmmmmma..........................',
    '.............................ammmmmmmmmmmmmmmmmmma...........................',
    '.............................ammmmmmmmmmmmmmmmmma............................',
    '..............................ammmmmmmmmmmmmmmmma............................',
    '...............................ammmmmmmmmmmmmmmaa............................',
    '................................aaammmmmmmmmmaama............................',
    '................................ammaammmmmmaammma............................',
    '................................ammmmaaaaaammaaa.............................',
    '.................................aaaama...ammmmma............................',
    '................................ammmmma...ammmmma............................',
    '................................ammmmma...ammmmma............................',
    '................................ammmmma...ammmmma............................',
    '................................aammmma...ammmma.............................',
    '.................................ammmma....aaaaaaaa..........................',
    '................................aaaaaa....attttttttaa........................',
    '..............................aatttttta..attttttttttta.......................',
    '............................aatttttttta..atttttttttttta......................',
    '...........................attttttttttta.atttttttttttta......................',
    '...........................attttttttttta..attttttttttta......................',
    '...........................attttttttttta...attttttttta.......................',
    '...........................atttttttttta.....aaaaaaaaa........................',
    '............................attttttaaa.......................................',
    '.............................aaaaaa..........................................']);
  add({id:'circusbaby', ic:'🤡', name:'Circus Baby'},
    {j:'#A5BF98', m:'#8D7F90', q:'#625956', b:'#A4462F', v:'#8F6467', s:'#3B3841', x:'#EAA229', u:'#7496F7', r:'#3D5EA7', g:'#F7EFED', k:'#A74C55', t:'#5B7DDE', n:'#B79FC3', h:'#3C3D75', f:'#1F1C45', p:'#F97A2B', w:'#141414', d:'#CFBDDC', a:'#7F2E1D', c:'#DE5737'}, [
    '................aaaaawbbbbb.................',
    '......aab.....aaabbbbwcccbbbb.....ccc.......',
    '.....abcwb...aabbbbccwcccccccb...bwbbb......',
    '....abcwbbawaabbbccccwcccccccccwccbwbac.....',
    '....abcwbaawaaabdbbdcwcdccdccccwccbwaac.....',
    '....ac...aawaaadfffggwgghhhdcccwcb...ac.....',
    '......b...awddgwgwgwgwgwgwgwgddwa...b.......',
    '.....bba.....ggwwwwg...gwwwwgg.....bbc......',
    '......aa....dwwwddgwgwgwddgwwwd....ac.......',
    '.....aa.....dggwdjwwgwgwwjdwggd.....ac......',
    '....aa......dggwdjjwgwgwjjdwggd......ac.....',
    '............dwwgggggbbbgggggwwd.............',
    '.............gggggggbbbggggggg..............',
    '............dggbbggggwggggbkggd.............',
    '............dgkbgwwwwwwwwwkgkgd.............',
    '.............dkbbgwwwwwwwgkkkd..............',
    '..............dkbggggwggggkkd...............',
    '................dddggwgggdd.................',
    '...................ddwgg....................',
    '.................ddwwwwwdd..................',
    '.........cccccwaawgggggggwcbwcccca..........',
    '........aacccaawaawwwgwwwccwcccccca.........',
    '..........aaaawacccccwccccccwcccc...........',
    '........mm....acccccccccccccc....jj..mmm....',
    '.......mmmdnwaacccccccccccccccwdnnnwmmmmm...',
    '.......mmmdnwaacccccccccccccccwndnnwmmmmm...',
    '.....nnwmdnnwaaaccccccccccccccwndwwnwmmm....',
    '.....ngnwnn..aaaacccwwwbccccccwnwdnnn.......',
    '....ngnnm.....aaawwwcccwwwccc...nddnwggg....',
    '....ngmmm........ddcccpcgg......nndwnwwg....',
    '.......m.......kdggccppcgggg.....nn..ggg....',
    '....mng........kggccwmwpcggg........nwwg....',
    '...mnggg.......kdgccmqmpcggg.........ggg....',
    '...mngwg........kdccwmwpcgg.................',
    '...mng........a...ccccpcc...a...............',
    '...mng.......acabawwwwwwwbacba..............',
    '....mng....aacacacbabacacbbaccaa............',
    '..........aabacabbabcabcacbcabcaa...........',
    '...........aaababbacaaacabbcabaa............',
    '..............aawwaa...aawwaa...............',
    '................kgwwmwmwwdd.................',
    '..............kdggnmmwmmmdggg...............',
    '..............kdggnmmwmmmdggg...............',
    '..............kdggnm...mmdggg...............']);

  /* ---------- mais Nintendo ---------- */
  add({id:'daisy', ic:'🌼', name:'Daisy'},
    {d:'#FBD216', g:'#D28E4F', f:'#CF670E', b:'#EE4682', w:'#FFFFFF', h:'#FCCF9A', c:'#08A0F4', j:'#D9A776', a:'#9C5711'}, [
    '............a.a.a...............',
    '...........abababa..............',
    '...........acbdbca..............',
    '..........aaabbaaaaa............',
    '.........afffaafffffa...........',
    '.......aaffffffffffffaa.........',
    '.......afffffaffffffffa.........',
    '.......affffaaafffffffa.........',
    '.......aaaghhhhhhggaaa..........',
    '.........aghahhahghgfa..........',
    '.........aghahhahhhgfa..........',
    '........afghhhhhhhggfa..........',
    '........afghhffhhgcfffa.........',
    '.........afghhhhggffffa.........',
    '.........aaaaaaaaaaaffa.........',
    '........addadwddadddafa.........',
    '........adadwcwdddddafa.........',
    '........adaddwddadddaa..........',
    '.........awaggggawwwaa..........',
    '.........ahawwwwwahaffa.........',
    '.........ahagggggahaaa..........',
    '..........awadddawaa............',
    '.........aawwadawwada...........',
    '.........aawwadawwadda..........',
    '........addaadddaaddda..........',
    '........addddddddddddda.........',
    '........addddddddddddda.........',
    '.......awgdgwgdgwgdgwgga........',
    '.......awwgwwwgwwwgwwwga........',
    '.......awwwwwwwwwwwwwwwa........',
    '.......awwwwwwwwwwwwwwwa........',
    '.......awwwwwwwwwwwwwwwa........']);
  add({id:'rosalina', ic:'⭐', name:'Rosalina'},
    {d:'#FF1F1F', g:'#FCD3A1', f:'#FFF30F', b:'#9C9C9C', w:'#FFFFFF', h:'#3CCFFC', c:'#3639F7', j:'#FF14C8', a:'#141414'}, [
    '...................a...aa...a.....................',
    '...................aa.awba.aa.....................',
    '...................abawbbbaba.....................',
    '...................acwbddbbca.....................',
    '................aaaacabwdbacaaaa..................',
    '...............afffabbbddbbbafffa.................',
    '..............afffffaabbbbaafffffa................',
    '...........a.affffafffaaaaffffffffa..a............',
    '...........aaffffaffffffffffffaffffaaa............',
    '...........affffaffffffffffffffafffffa............',
    '............affaaffffffffffffffafaffa.............',
    '............aaaafffffffffffffffaffaaa.............',
    '.........a..affafffffffffffffffaffffa..a..........',
    '.........aaafffafffffffffffffffafffffaaa..........',
    '.........afffffaffffffffffffffaffffffffaa.........',
    '..........affffaffffffffffffaaffffffffa...........',
    '...........afffafffffffffffaggaafffffa............',
    '............aaaaffffffffffagaaaaaaaaa.............',
    '.............agafffffffffagaawhafaga..............',
    '.............agafaffffffaggaaawafaga..............',
    '.............agafaffffffaggaccwafaga..............',
    '............awaafafffffaggggaawafaa..a............',
    '............aaaaffafffaggggggggafaa.aa............',
    '............afaaafafffagjjggggaafaaafa............',
    '............afffafaafaagggggaaaafafffa............',
    '............affffagafagaaaaggaggaffffa............',
    '.............affawwwawwggggwwawwwaffa.............',
    '..............aaawwwwwwwaawwwwwwwaaa..............',
    '...............aaawwahhaffahhawwaaa...............',
    '...............ahhaahhhaffahhhaahha...............',
    '.............aahhha.ahhhaahhha.ahhhaa.............',
    '............awwhhha..aaaccaaa..ahhhwwa............',
    '............awwwwa...ahchhcha...awwwwa............',
    '.............agwwa..ahchhhhcha..awwga.............',
    '.............aggwa.ahhchhhhchha.awgga.............',
    '.............agga..ahchhhhhhcha..agga.............',
    '..............aa..ahhhhhhhhhhhha..aa..............',
    '..................ahhhhhhhhhhhha..................',
    '.................ahhhhhhhhhhhhhha.................',
    '.................ahhhhhhhhhhhhhha.................',
    '.................ahhhhhhhhhhhhhha.................',
    '................ahhhhhhhhhhhhhhhha................',
    '................ahhhhhhhhhhhhhhhha................',
    '...............ahhhhhhhhhhhhhhhhhha...............',
    '..............awhhhhhhhhwwhhhhhhhhwa..............',
    '..............awwhhhhhhhwwhhhhhhhwwa..............',
    '...............awwhhhhhwccwhhhhhwwa...............',
    '................awwhhhhwccwhhhhwwa................',
    '.................awwwwwccccwwwwwa.................',
    '..................aaaaaaaaaaaaaa..................']);
  add({id:'zelda', ic:'🔺', name:'Zelda'},
    {m:'#F7ACFE', d:'#F3DEC1', g:'#73BCFB', f:'#F92F2F', b:'#EBC62D', w:'#FFFFFF', k:'#AA65F9', h:'#EB5BF8', c:'#FCDE58', j:'#C292FA', a:'#141414'}, [
    '......a..aaaaaa..a......',
    '........abbbbbba........',
    '.....awabccccccbawa.....',
    '.....a.bccccccccb.a.....',
    '.....a.bccccccccb.a.....',
    '....aa.bccccccccb.aa....',
    '...ada.bbccbbccbb.ada...',
    '...addababbwfbbabadda...',
    '....adabcaaffaacbada....',
    '.....aabcccaacccbaa.....',
    '.....abdagddddgadba.....',
    '....abcdwgddddgwdcba....',
    '....abcaddddddddacba....',
    '....abbhaddddddahbba....',
    '....abadhaaaaaahdaba....',
    '.....awdajjjjjjadwa.....',
    '.....awwacjjjjcawwa.....',
    '....awwahkcccckhawwa....',
    '.....aahmmkcckmmhaa.....',
    '.....ahmmmkkkkmmmha.....',
    '.....ahhmmkkkkmmhha.....',
    '......ahhhkkkkhhha......',
    '.......aahhkkhhaa.......',
    '.........aaaaaa.........']);
  add({id:'toad', ic:'🍄', name:'Toad'},
    {k:'#262626', w:'#F7F7F7', r:'#F42A14', s:'#FFCBA0', e:'#262626', b:'#0047BB', n:'#7A4A08', lid:'s'}, [
    '...........kkkkkkk............',
    '.........kkwwwwwwwkk..........',
    '........kwwwrrrrwwwwk.........',
    '.......kwwwrrrrrrwwwwk........',
    '......kwwwrrrrrrrrwwwwk.......',
    '......krwwrrrrrrrrwwwrk.......',
    '.....krrrwrrrrrrrrwwrrrk......',
    '.....krrrwwrrrrrrwwrrrrk......',
    '.....krrrwwwrrrrwwwrrrrk......',
    '.....krrrwwwwwwwwwwrrrrk......',
    '.....krrwwwkkkkkkkwwrrrk......',
    '......kwwwkssssssskwwrk.......',
    '......kwwkssessesskwwwk.......',
    '.......kkkssessessskwk........',
    '.........kssssssssskk.........',
    '.........kssskkssssk..........',
    '..........ksssssssk...........',
    '...........kkkkkkkbk..........',
    '.........kkbkssskbbkk.........',
    '........kskbkssskbbkskk.......',
    '.......ksskbkssskbbksssk......',
    '......kssskbkkkkkkbbksssk.....',
    '......kssskkwwwwwwkbksssk.....',
    '.......kkkkwwwwwwwkkkkkk......',
    '..........kwwwwwwwwkk.........',
    '........kkkkwwwwwkkkk.........',
    '.......knnnnkkkkknnnnk........',
    '.......knnnnnk.knnnnnk........',
    '........kkkkk...kkkkk.........',
    '..............................']);
  add({id:'boo', ic:'👻', name:'Boo'},
    {w:'#FFFFFF', a:'#141414', b:'#FF0001'}, [
    '................',
    '.....aaaaa......',
    '...aawwwwwaa....',
    '..awwwwwwwwwa...',
    '.awwwwwwwwwwwa..',
    '.awawawwwwwwwa..',
    'awwawawwwwaawwa.',
    'awwwwwwwwawwawa.',
    'awbwbwbwwwwwawa.',
    'awbbbbbwwwwawwwa',
    'awbbbbbwwwwwwwwa',
    '.awbbbbbwwwwwwwa',
    '.awbwbwbwwwwwwa.',
    '..awwwwwwwwwaa..',
    '...aaawwwwaa....',
    '......aaaa......']);
  add({id:'eevee', ic:'🦊', name:'Eevee'},
    {c:'#1B1D1D', w:'#FFFFFF', a:'#141414', d:'#F9E29D', b:'#A65E21'}, [
    '..aa..................aa......',
    '..aba................aba......',
    '..abba..............abba......',
    '..ababa............cbaba......',
    '..abaaba..........abaaba......',
    '..abaaaa...aa.....aaaaba......',
    '..abaaaa.aabaaaa..aaaaba......',
    '...abaaaabbbbbbbaaaaaba.......',
    '....ababbbbbbbbbbbbaba........',
    '.....abbbbbbbbbbbbbba.........',
    '.....abbbbbbbbbbbbbba.........',
    '....abbbbbbbbbbbbbbbba........',
    '....abbadabbbbbbadabba........',
    '....abbaaabbbbbbaaabba...a....',
    '....abbaaabbbbbbaaabba..ada...',
    '....abbaaabbabbbaaabbaaadda...',
    '....abbbbbbbbbbbbbbbbadddda...',
    '.....abbbbbaaaabbbbbabdddda...',
    '.....aabbbbbbbbbbbbaabbddda...',
    '....addaabbbbbbbbaaddabbdda...',
    '....addddaaaaaaaaddddabbbba...',
    '....addddddddddddddddabbbba...',
    '.....addaddddddddaddabbbba....',
    '......aaaddddddddaaaabbbba....',
    '.....abbbaddddddabbbabbba.....',
    '.....abbbbaaddaabbbbabba......',
    '.....abbabbbaabbbabbaaa.......',
    '......ababbbaabbbabc..........',
    '.....abbabbbaabbbabba.........',
    '.....aaaaaaa..aaaaaaa.........']);
  add({id:'jigglypuff', ic:'🎤', name:'Jigglypuff'},
    {d:'#046186', g:'#8CC4C9', f:'#539FB4', b:'#ECBAC4', w:'#FFFFFF', c:'#DA7488', a:'#141414'}, [
    '...................................................',
    '...................................................',
    '...................................................',
    '............aaaa...................................',
    '...........abbbba..................................',
    '..........abaabbbaa................................',
    '..........acaaabbbba...............................',
    '..........aaaaaabbbba..............................',
    '.........abaaaaaabbbba..aaaaaaaa...................',
    '.........abaaaaaaabbbbaabbbbbbbba..................',
    '.........acaaaaaaaabbabbbbbbbbbbba.................',
    '.........acaaaaaabbbabbbbbbbbbbbbba................',
    '.........acaaaabbbbabbbbbbbbbbbbbbba...............',
    '.........acaabbbbbabbbbbbbbbbbbbbbba...............',
    '........accabbbbbbabbbbbbbbbbbbbbbba...............',
    '........aabbbbbbbabbbbbbbbbbbbbbbbbaa..............',
    '........abbbbbbbbabbbbbbbbbbbbbbbbabbaaaaaaaa......',
    '.......abbbbbbbbbabbbbbbbbbbbbbbbbbbbbbbbbbbbaa....',
    '.......abbbbbbbbbabbbbbbbbbcccccaabbbbbbbbbbbbbaaa.',
    '......abbbbaaaaababbbbbbbbaaaaaacbbbbbbaaaaaaaabbba',
    '......abbbawwaaaaabbbbbbbaccacccbbbbbbbaaaaaaaaaaba',
    '.....abbbawwaddwwabbbbbbacccaccbbbbbbbbbaaaaaaaaca.',
    '.....abbawwadddwwaabbbbbbbccacbbbbbbbbbbaaaaaaaaca.',
    '.....abbawaddddddaabbbbbbbcacbbbbbbbbbbbbaaaaaaca..',
    '....abbbawaddddddaaaabbbbcaccbbbbbbbbbbbbaaaaaca...',
    '....abbbawadfffddaabbaaaaaccaaaaaabbbbbbbaaaacba...',
    '....abbbawafgggfdabbbbcccccawwaaaaabbbbbbaaacba....',
    '....abbbawwagggfaabbbbbbbbawwaddwwaabbbbbbacba.....',
    '....abbbbawwaaaaabbbbbbbbbawadddwwdaabbbbbcaa......',
    '..aaabbbbbawwwaabbbbbbbbbawwaddddddaabbbbba........',
    'aabbacbbbbbaaabbbbbbbbbbbawwaddddddaabbbba.........',
    'abbbaccbbbbbbbbbbabbbbbbbawwadffffdaabbbba.........',
    'abbbbcccbbbbbbbbbbabbbbbbawwafgggfdabbbbba.........',
    '.abbbccccbbbbbbbbbbaaaaabbawafgggfaabbbbba.........',
    '..aacaccccbbbbbbbbbbbbbbbbawwaaaaaabbbbbba.........',
    '....aaaccccbbbbbbbbbbbbbbbbaawwwwabbbbbba..........',
    '......accccccbbbbbbbbbbbbbbbbaaaabbbbbbca..........',
    '.......acccccccbbbbbbbbbbbbbbbbbbbbbbbca...........',
    '.......accccccccccbbbbbbbbbbbbbbbbbbccca...........',
    '........acccccccccccccbbbbbbbbbbbbaccca............',
    '.........acccccccccccccccccccabbbbacca.............',
    '..........accccccccccccccccccabbbbaca..............',
    '........aacacccccccccccccccccacbbcaa...............',
    '.......abbccccccccccccccccccccaccca................',
    '......abbbbcccaccccccccccccccccaca.................',
    '.....abbbbbbcccaaaccccccccccccacaba................',
    '.....abbbbbbcaa...aaaaaaaaaaaccbbbba...............',
    '......aaaaaaa..............accbbbbbba..............',
    '............................acbbbbbba..............',
    '.............................aaabbba...............',
    '................................aaa................']);

  /* turma da Hello Kitty */
  add({id:'hellokitty', ic:'🎀', name:'Hello Kitty'},
    {c:'#FFEB3B', w:'#FFFFFF', a:'#141414', d:'#1565C0', b:'#CC0B08'}, [
    '.........aaa..................',
    '.....aaaaabba........aaa......',
    '....awwaaabbbaaaaa.aawwa......',
    '....aaaabaabbawwwwawwwwwa.....',
    '...abbabbbabbawwwwwwwwwwa.....',
    '...abbaabaaaawwwwwwwwwwwa.....',
    '...abbbaaawwwwwwwwwwwwwaa.....',
    '...abbbawwwwwwwwwwwwwwwwa.....',
    '....aaawwwwwwwwwwwwwwwwwwa....',
    '....awwwwwwwwwwwwwwwwwwwwa....',
    '....awwwwwwwwwwwwwwwwwwwwa....',
    '...aaawwwaawwwwwwwwaawwwaaa...',
    '....awwwwaawwwwwwwwaawwwwa....',
    '....aawwwaawwwwwwwwaawwwaa....',
    '...aawwbbwwwwwccwwwwwbbwwaa...',
    '.....awwwwwwwwwwwwwwwwwwa.....',
    '.....aawwwwwwwwwwwwwwwwaa.....',
    '....a..aawwwwwwwwwwwwaa..a....',
    '........aaaaaaaaaaaaaa........',
    '.......acaddaccccaddaca.......',
    '......acadaddaaaaddadaca......',
    '.....aacaawaddddddawaacaa.....',
    '....awwaadaddddddddadaawwa....',
    '....awwaddddddddddddddawwa....',
    '....awwaddddddddddddddawwa....',
    '.....aaaddddddddddddddaaa.....',
    '.......aaddddddadddddaa.......',
    '.......awaaaaaaaaaaaawa.......',
    '.......awwwwwwwawwwwwwa.......',
    '........aaaaaaa.aaaaaa........']);

  add({id:'mymelody', ic:'🐰', name:'My Melody'},
    {c:'#FEE9B4', w:'#FFFFFF', a:'#141414', b:'#F2B8B6'}, [
    '....aaaaaa........aaaaa........',
    '...abbbbbbaa....aabbbbba.......',
    '..abbbbbbbbba..abbbbbbbba......',
    '..abbbbbbbbbbaabbbbbbbbba......',
    '..abbbbbbbbbbbabbbbbbbbba......',
    '...abbaabaabbbabbbbbbbbba......',
    '....aawwawwabbabbbbbbabba......',
    '.....awwwwwabbbabbbbabbba......',
    '.....aawcwabbbbbaaaabbbbba.....',
    '....aawwwwwabbbbbbbbbbbbbba....',
    '...abawwawwabbbbbbbbbbbbbbba...',
    '...abbaabaaaaaaaaaaaaabbbbba...',
    '...abbbbawwwwwwwwwwwwwabbbba...',
    '...abbbawwwwwwwwwwwwwwwabbba...',
    '...abbawwwwwwwwwwwwwwwwwabba...',
    '...abbawwaawwwwwwwwwaawwabba...',
    '...abbawwaawwwwwwwwwaawwabba...',
    '...abbawwaawwwcccwwwaawwabba...',
    '....abawccwwwwwwwwwwwccwaba....',
    '.....abaccwwwwwwwwwwwccaba.....',
    '......aaaaaaaaaaaaaaaaaaa......',
    '........abbbbawwaabbbba........',
    '........aabbawwwwwabbaa........',
    '.......awaaawwwwwwwaaawa.......',
    '......awwawwwwwwwwwwwawwa......',
    '......awwawwwwwwwwwwwawwa......',
    '.......aaawwwwwwwwwwwaaa.......',
    '.........awwwwwwwwwwwa.........',
    '.........awwwwwwwwwwwa.........',
    '.........awwwaaaaawwwa.........',
    '..........aaa.....aaa..........']);

  add({id:'kuromi', ic:'💀', name:'Kuromi'},
    {d:'#E985CB', g:'#FFE79B', f:'#FFFFFF', b:'#444444', w:'#FFFFFF', h:'#FF01FF', c:'#606060', a:'#141414'}, [
    '..aaa.........................',
    '..abaaaaaaaa..........aaaaaa..',
    '..aaabbbbbbba........abbbbbb..',
    '...abbbbbbbba........abbbbbb..',
    '...abbbbbbaaaaaaaaaaaaaabbbb..',
    '...abbbbbabbbbbbbbbbbbbbabbb..',
    '...abbbbabbbbbbbbbbbbbbbbabb..',
    '...abbbabbbbbbbwwwwbbbbbbbab..',
    '...abbabbbbbbbwbwwbwbbbbbbba..',
    '...abbabbbbbbbwbwwbwbbbbbbba..',
    '....aabbbbbbbbbwwwwbbbbbbbbb..',
    '.....abbbbbaaabbwwbbaaabbbbb..',
    '.....abbbbafffabbbbafffabbbb..',
    '.....abbbafffffabbafffffabbb..',
    '.....abbafafffffaafffffafabb..',
    '.....abbaffaaffffffffaaffabb..',
    '.....abbafaaaffffffffaaafabb..',
    '.....abbaffaafffwwfffaaffabb..',
    '......abafwwffffffffffwwfaba..',
    '.......afawwffffafffffwwafa...',
    '........aaaaaaaaaaaaaaaaaa....',
    '......a...abbbbbaabbbbba......',
    '.....aba.daaabbaffabbaaad.....',
    '....abbbaafafaaffffaafafa.....',
    '.....abaaffafdffffffdfaffa....',
    '.....abaaffaffffffffffaffa....',
    '......abbaaaffffffffffaaa.....',
    '.......aaaaaffffffffffa.......',
    '...........afffaaaffffa.......',
    '............aaaa..aaaa........']);

  add({id:'cinnamoroll', ic:'☁️', name:'Cinnamoroll'},
    {d:'#2770AF', f:'#FF5E7D', b:'#C8D9CC', c:'#FFFFFF', a:'#141414'}, [
    '..............................',
    '..............................',
    '..............................',
    '..............................',
    '..............................',
    '..............................',
    '..............................',
    '..............................',
    '..............................',
    '..............................',
    '..............................',
    '.............aaaaaaa..........',
    '.........aaaabbbbbbbaaaa......',
    '........acbbbcccccccbbcca.....',
    '.......acbbcccccccccccbcca....',
    '......accbcccccccccccccbcba...',
    '......acbacccccccccccccacca...',
    '.....abcabcddcccccccddccacca..',
    '..aaabcbabcddcccccccddccaccba.',
    '.abbbccbabcddcacacacddccaaccba',
    'abcccccbabffcccacacccffbacccba',
    'abccccbbabbcccccccccccbabcccba',
    '.abbbbba.aabaaabbbaabbaabbbba.',
    '..aaaaa....aaffaaaffaa..aaaa..',
    '..........acafffafffaca.......',
    '..........acaafffffaaca.......',
    '..........aaccafffaccaa.......',
    '.........acccccafaccacca......',
    '.........abbbbbbabbbbbba......',
    '..........aaaaaaaaaaaaa.......']);

  add({id:'pompompurin', ic:'🍮', name:'Pompompurin'},
    {d:'#DE835B', g:'#FF8D71', f:'#F8E8A7', b:'#C8424B', w:'#F2E4E7', h:'#F1C690', c:'#853B36', j:'#D67881', a:'#E5B5C8'}, [
    '.................................................',
    '........................bc.......................',
    '......................bbbcccc....................',
    '....................bbbbbdcccccc.................',
    '..................bbbdddddccbdbcc................',
    '..................bddffdddddddddcc...............',
    '................bcbbdddddddddddcccc..............',
    '..............bbbffbbbbbbccccccccdccc............',
    '.............bbfffffffbbbbcccdddffffbbd..........',
    '............bbffffffffffffffffffffffffbb.........',
    '..........bbfffffffffffffffffffffffffffbb........',
    '........bbbffffffffffffffffffffffffffffffbb......',
    '......bbbfffffffffffffffffffffffffffffffffbb.....',
    '.....bbffffffdffffffffffffffffffffffdfffffffbb...',
    '....bbffffffddffffcfffffffffffffffffdffffffffbb..',
    '...bdfffffffbffffccfffffffffffccffffdbffffffffbb.',
    '..bbfffffffbgffffffffffccgfffffffffffbfffffffffb.',
    '..bfffffffgbffffffffffffgffffffffffffbgffffffffcc',
    '.bbfffffffbbfffhhhhffffffffffffhhhfffbbffffffffgc',
    '.bbfffffffcffffhhhhffccccccfffhgghfffgcgfffffffgc',
    '.bbffffffccfffffffffffffffffffffffffffccgfffffggc',
    '..bfffffgccfffffffffffffffffffffffffffgcgggggffcc',
    '..bbfffggcgffffffffffffffffffffffffffffccgggfggcc',
    '...cccccccfffffffffbgffgbgffffffffffffffcccccccc.',
    '.....cccccfffffffbbbbgbbbbgffffffffffffffdccccg..',
    '.......bbfffffffbbgggbbdjbcgffffffffffffffcc.....',
    '.......bfffggggbbjgfggjgjjbbbffffgffffffffgc.....',
    '......bbffffggbbbbbgfhgjjbbbbbcccgfffffffffc.....',
    '......bffffffffffgbggggjjbgfffcccffffffffffcc....',
    '......bfffffffffffbjgggjbbfffffffffffffffffgc....',
    '......bgffffffffffbcgggjbbffffffffffffffffffc....',
    '......bbffffffffffccbjcccbffffffffffffffffffcc...',
    '....bbcbbffffffffccggbcggbbffffffffbgfffffffcc...',
    '..bbbbbgcccffffcccgfffffffcccgfffccbffffffffcccc.',
    '.bbgfffcgdccccccgffffffffffdccccccggfffffffgcccc.',
    '.bgfffffgffffffffffffffffffffffffffffffffffgccgcc',
    '.bffffffffffffffffffffffbbbbfffffffffffffffgccggc',
    'bbfffffffffffffffffffffbbffbbfffffffffffffggcgggc',
    'bbffffffffffffffffffffbbffffbgffffffffffffggcgggc',
    'bbffffffffggffffffffffbgfffffgfffffffffffggccggcc',
    '.bffffffffgggfffffffffbffffffffffffffffggggcgggcc',
    '.bgffffffggbgggffffffbbffffffffggffffgggggccgggc.',
    '.bbffffffgccgggggggggbcffffffffgggggggggggcccccc.',
    '..bbgfffgcccccgggggggccffffffffggggggggggcc......',
    '...ccccccc...ccccgggggcffffffffgggggggggcc.......',
    '.....ccc.......ccccccbccffffffggcgggccccc........',
    '..................cccccccfffffgccccccc...........',
    '........................ccgggbccc................',
    '.........................cccccc..................']);

  /* ---------- 🎃 Halloween (quem tem faca: "knife" = pedaço que levanta e dá a facada) ---------- */
  add({id:'ghostface', ic:'👻', name:'Ghostface', knife:[8, 27, 1, 6]},
    {d:'#E4DEDF', g:'#545350', f:'#B3B2B0', b:'#141414', w:'#151515', k:'#272626', h:'#9B999A', c:'#FFFFFF', j:'#757575', a:'#FC0504'}, [
    '................bbbbbbbbbbb..........',
    '..............wbbbbbbbbbbbbbw........',
    '............bbbbbbbbbbbbbbbbb........',
    '...........wbbbbbbbbbbbbbbbbw........',
    '..........wbbbbbbbbbbbbbbbbb.........',
    '..........wbbccccccbbbbbbbb..........',
    '..........wbccccccccbbbbbbbb.........',
    '.........bbbcccccccccdbbbbbb.........',
    '........bbbccccccccdddbbbbbbb........',
    '.....bb.bbbcccdcccccdddbbbbbb........',
    '....wfb.bbbccdbbcbbddddbbbbbb........',
    '...wgfb.bbbccdwbcbbddddbbbbbb........',
    '...bgfb.bbbcdbbbcbbbddddbbbbb........',
    '...bghb.bbbcbbbbcbbbbdddbbbbb........',
    '...bghw.bbbdbbbdccbbbdddbbbbb........',
    '...bghw..bbdbbbdccbbbdddbbbbw........',
    '...bgjb..bbddddcbccdddddbbbb.........',
    '...bgjb..bbccccbbbcddddbbbbbbb.......',
    '...bgjb...wbcccdddccddbbbbbbbbw......',
    '...bgbbbwwbbbcccbbccddbbbbbbbbbb.....',
    '..bbbwgbbbbbbbcbbbbdddbbbbbbbbbbb....',
    '..bwgggbbbbbbbcbbbbdbbbbbbbbbbbbbb...',
    '..bwgggbbbbbbbcbbbbdbbbbbbbbbbbbbb...',
    '..bwggwbbbbbbbcdbbddbbbbgwwbbbbbbbb..',
    '..bwwwwbbbbbbbbdbbdbbbbgggwwbbbbbbb..',
    '...bbbbbbbbbbbbdbbdbbbbgggwwbbbbbbb..',
    '...bjbbbbbbbbbbddddbbbbgggwwbbbbbbb..',
    '...bbbbbbbbbbbbbbbbbbbbggggwbbbbbbb..',
    '......bbbbbbbbbbbbbbbbbbgggwbbbbbb...',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbb....',
    '......bbbbb.bbbbbbbbbbbbbbbbbbbb.....',
    '......bbb..bbbbbbbbbbbbbbbbbbbbb.....',
    '......bb...bbbbbbbbbbbbbbbbbbbbb.....',
    '...........bbbbbbbbbbbbbbbbbbbbb.....',
    '..........wwgggbbbbbbbbbbbbbwggkb....',
    '.........bkgggggww.....bbwwwwwggwb...',
    '........wbbbbbbbbb.......bbbbbbbbb...']);
  add({id:'jason', ic:'🏒', name:'Jason', knife:[5, 28, 1, 8]},
    {j:'#979797', m:'#392313', q:'#22273B', b:'#040200', w:'#1E1E1E', g:'#D0A07E', k:'#AD1B16', n:'#A0623C', h:'#BB7F68', f:'#828665', p:'#515151', d:'#B2B695', a:'#F90300', c:'#E6E8C1'}, [
    '............bbbbbbbbbbbbb............',
    '...........bcccccccccdfghb...........',
    '..........bccbccccbccdfgghb..........',
    '.........bcccdccccdccdffgghb.........',
    '.......bbbcccbccccbccdddfgghb........',
    '......bfbccccdcbccdccccdfggghb.......',
    '.....bfbcccccccdcccccccdffgghb.......',
    '....bfjbcccccaaaakkccccddfghmmb......',
    '....bfjbcccccdaakkdcccccdfmmmwb......',
    '....bfjbccccccdakdccccccdfmnwwb......',
    '....bfjbcccbbbcddcbbbcccdfwwwhb......',
    '....bfjbccbbbbccccbbbbbcdfwhhhb......',
    '....bfjbccbbbbccccbbbbbcdfhghb.......',
    '....bfjbccbbbdccccddbbbddfghhb.......',
    '....bpjbccdddcccccccddddfgghb........',
    '....bpjjbc.kcbcccbc..dddfghbb........',
    '....bpfjb.ddcdcccdcdd.kdfgbwwb.......',
    '....bppjbbcccbcccbcccdddfbppwwb......',
    '....bppfb.bccdcccdcccddfbppppwwb.....',
    '....bppfb..bbcbcccbcddbbppppppwwb....',
    '...bbbbbb..bpbbbbbbbbbbppppppppwwb...',
    '..bbppppbbbpppppqqqqqqqppppwbppwwb...',
    '..bppppppppppppppqqqqqqpppwwwbwwwb...',
    '..bqppqqpppppwwppqqqqqqppwwwwbppwwb..',
    '..bqqqqqqppwwbbwpqqqqqppwwwwbbpppwb..',
    '..bqqqqqqppwwb.bpqqqqqpppwwbpqqpwwb..',
    '..bqqqqqppwwb..bpqqqqqppwwbbpppqqqb..',
    '..bbbqqqpbbb..bpppqqqpppwbpppppppqb..',
    '....bbbbbb...bwqppppppppqbbpppppqqb..',
    '....bqqqb.w.bpppqqqbbbwqppbbpppqqbb..',
    '.....bbb...bppppppb...bppppqbbbbb....',
    '...........bppppppb...bbppppppb......',
    '...........bpppppb......bppppppb.....',
    '..........bppppppb.......bppppppb....',
    '.........bwqqqqqpb.......bpwqqqwwb...',
    '........bwqqqqqqqb.......bwwqqqqwb...',
    '........bbbbbbbbbb.......bbbbbbbbb...']);
  add({id:'chucky', ic:'🔪', name:'Chucky', knife:[18, 28, 7, 11]},
    {d:'#17E61A', g:'#0055FF', f:'#FF0019', b:'#FF7700', w:'#FFFFFF', h:'#E62968', c:'#FFE8AD', j:'#595959', a:'#141414'}, [
    '.................aaaa................',
    '................abbbbaaa.............',
    '............aa.abbbbbbbbaa...........',
    '..........aabbabbbbbbbbbbba..........',
    '.........abbbbbbbbbbbbbbbbba.........',
    '........abbbbbabaaaabbbbbbba.........',
    '........abbbbacaccccaabbbbbba........',
    '.......abbbbacccccccccabbbbba........',
    '.......abbbbaccccccccccaabbba........',
    '........abbabcccccccccccbabbba.......',
    '........abbacbbcccccccbbcabbba.......',
    '.......abbaccccbbcccbbccccabba.......',
    '.......abbaccaaccbcbccaaccabba.......',
    '.......abbaccaacccccccaaccabba.......',
    '.......abbacccccccccccccccabba.......',
    '........aacccccccccccccccccaa........',
    '.........accccccccccccccccca.........',
    '..........accccccaaaccccccaa.........',
    '.........aaaccccccccccccca...........',
    '........aacaaaccccccccaaa............',
    '.......acacaaaaaaaaaaada.............',
    '.......accaafgdadgdgdadda............',
    '........aaahfgdagfgfgagga............',
    '........ajaaaaagggggggaffa...........',
    '........aja...agggggggaahha..........',
    '........aja...agggggggaaffaa.........',
    '........aja...aggggggga.aacca........',
    '........aa....aggggggga..acca........',
    '........a....aggggggggga..aa.........',
    '.............aggggggggga.............',
    '.............aggggagggga.............',
    '.............aggga.aggga.............',
    '.............afgda.adgfa.............',
    '.............afgda.adgfa.............',
    '.............aaaaa.aaaaa.............',
    '............afwffa.affwfa............',
    '...........af.fffa.afff.fa...........']);
  add({id:'michaelmyers', ic:'🎃', name:'Michael Myers', knife:[6, 15, 18, 26]},
    {d:'#C7C7C7', g:'#303030', f:'#E9C185', b:'#241A07', w:'#FFFFFF', k:'#8D8D8D', h:'#C6A36F', c:'#A9A9A9', j:'#1D2041', a:'#141414'}, [
    '...........................',
    '...........................',
    '...........................',
    '........aaaaaa.............',
    '.......abbbbbba............',
    '......abbbbbbbba...........',
    '......abbccccccca...aa.....',
    '.....abbccccdddca..affa....',
    '.....acbccbbcdcba.agghha...',
    '.....accdcaabcbaa.afggga...',
    '......acdcaaacaaaagfhgada..',
    '.....aacdccccdccajjjjakkda.',
    '...aajjacdcaaadajjjja.akkda',
    '..ajjjjjacdcccajjjja...akka',
    '..ajjjjjjaaaaajjjja.....aka',
    '.ajjjjajjbbbjjajja.......aa',
    '.ajjjaajjjbjjjaaa..........',
    '.ajjawajjjjjjja............',
    '.afhhaajjjjjjja............',
    '.affhaajjjjjjja............',
    '..aaawajjjjjjja............',
    '.....ajjjjajjjja...........',
    '....ajjjja.ajjjja..........',
    '...aajjjja.ajjjjaa.........',
    '.aabbbjja...ajjbbbaa.......',
    'abbbbbbba...abbbbbbba......',
    'aaaaaaaaa...aaaaaaaaa......']);
  add({id:'bruxa', ic:'🧙', name:'Bruxa', knife:[36, 48, 12, 21]},
    {j:'#555555', m:'#5CF37F', q:'#613B2E', b:'#451F55', w:'#FFFFFF', r:'#836291', g:'#717171', k:'#33A458', n:'#134B2B', h:'#A3A3A3', f:'#3DBE65', p:'#0E0F11', d:'#474747', a:'#1B1C20', c:'#237A43'}, [
    '........................................aaa...................',
    '......................................aaaaa...................',
    '....................................aaaaaaa...................',
    '..................................aaaaaaaaa...................',
    '................................aaaaaaaaaa....................',
    '..............................aaaaaaaaaaaa....................',
    '............................aaaaaaaaaaaaa.....................',
    '..........................aaaaaaaaaaaaaaa.....................',
    '........................aaaaaaaaaaaaaaaa......................',
    '.........aaaaaaaaaa...aaaaaaaaaaaaaaaaaa......................',
    '.......aaaaaaaaaaaaabbaaaaaaaaaaaaaaaaaa......................',
    '......aaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaa.......................',
    '.....aaaaaaaaaaaaaaabbbbaaaaaaaaaaaaaaa.......................',
    '.....aaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaa........................',
    '......aaaaaaaaaaaaaaabbbbbbaaaaaaaaaaa........................',
    '.......aaaaaaaaaaaaaaabbbbbbbaaaaaaaaaa.......................',
    '.........aaaaaaaaaaaaaabbbbbbbbbaaaaaaaaa.....................',
    '...........aaaaaaaaaaaaaabbbbbbbbbbbaaaaaaa...................',
    '.............aaaaaaaaaaaaaabbbbbbbbbaaaaaaaa..................',
    '...............caaaaaaaaaaaaaaabbbbaaaaaaaaaa.................',
    '...............ccccaaaaaaaaaaaaaaaaaaaaaaaaaaa................',
    '...............ccccccddaaaaaaaaaaaaaaaaaaaaaaa................',
    '...............cffffgdddccccdgaaaaaaaaaaaaaaa.................',
    '...............cfffggcccccccdggggdaaaaaaaaaa..................',
    '................cfggfddddfffcdggghdggaaaaaa...................',
    '................cfgfdaaagfffccddgghdgghgjghj..................',
    '................cfffdgaawffffcccdgghdghgjgghj.................',
    '...............kkfffgwwffccfffcccdghdgaagjgaaj................',
    '.............kkmmmfffffccffffffccdghjgghaaaghj................',
    '.............kmfmmfffffffffffffccdghjgaaaaaaaj................',
    '............kmffmffccffffffffffcndgghjggagaggj................',
    '...........kmmmmffffcffffffffffnccdgghjaggdagj................',
    '...........kmmfffffcccffbbffffnccpadgghjgddddaa...............',
    '...........kffffccc...bbfffffnccpaaadghjdaaaaaaa..............',
    '............cccc......cffffnn.ppaaaadgddaaaaaaaaa.............',
    '.......................ccnn...paaaaaddaaaaaaaaaaaa............',
    '................qqq..........paaaaaaaaaaaaaaaaaaaa............',
    '................qqq.........paaaaaaaaaaaaaaaaaaaaaa...........',
    '................rqr.......ppaaaaaaapaaaaaaaaaaaaaaa...........',
    '................rwr....pppaaaaaaaaapaaaaaaaaaaaaaaa...........',
    '................rwrppppaaaaaaaaaaapaaaaaaaaaaaaaaaa...........',
    '...............ffwwraaaaaaaaaaaaaapaaaaaaaaaaaaaaaa...........',
    '..............rffffffaaaaaaaaaaaapaaaaaaaaaaaaaaaaa...........',
    '.............rbbffffffaaaaaaaaaaapaaaaaaaaaaaaaaaaap..........',
    '.............rbrffffffaaaaaaaaappaaaaaaaaaaaaaaaaaap..........',
    '.............rbbbbffffaaaaaaappaaaaaaaaaaaaaaaaaaaap..........',
    '.............rbbbbbbbraaaaaapaaaaaaaaaaaaaaaaaaaaaap..........',
    '..............rbbbbbraaaaaappaaaaaaaaaaaaaaaaaaaaaap..........',
    '...............rrrrraaaaaap.paaaaaaaaaaaaaaaaaaaaaap..........',
    '.....................aaaap..paaaaaaaaaaaaaaaaaaaaaap..........',
    '.....................aaap...paaaaaaaaaaaaaaaaaaaaaap..........',
    '.....................ppp....paaaaaaaaaaaaaaaaaaaaaaap.........',
    '...........................paaaaaaaaaaaaaaaaaaaaaaaap.........',
    '...........................paaaaaaaaaaaaaaaaaaaaaaaap.........',
    '...........................paaaaaaaaaaaaaaaaaaaaaaaap.........',
    '...........................paaaaaaaaaaaaaaaaaaaaaaaap.........',
    '..........................paaaaaaaaaaaaaaaaaaaaaaaaap.........',
    '..........................paaaaaaaaaaaaaaaaaaaaaaaaaap........',
    '..........................paaaaaaaaaaaaaaaaaaaaaaaaaap........',
    '..........................paaaaaaaaaaaaaaaaaaaaaaaaaap........',
    '.........................paaaaaaaaaaaaaaaaaaaaaaaaaaap........',
    '.........................paaaaaaaaaaaaaaaaaaaaaaaaaaaapp......']);

  /* coloca os personagens na ordem da lista GRUPO (bichinhos continuam primeiro) */
  const ordem = Object.values(GRUPO).flat(), pos = p => p.special ? ordem.indexOf(p.id) : -1;
  const bichos = Pets.LIST.filter(p => !p.special), especiais = Pets.LIST.filter(p => p.special).sort((a, b) => pos(a) - pos(b));
  Pets.LIST.splice(0, Pets.LIST.length, ...bichos, ...especiais);
})();
